// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace IoT.DriverCore.ModbusRx.Generators;

/// <summary>Generates Modbus-backed reactive properties and observable streams.</summary>
public sealed partial class ModbusReactiveStreamGenerator
{
    /// <summary>Emits the generated partial class source.</summary>
    /// <param name="classSymbol">The class symbol.</param>
    /// <param name="points">The generated points for the class.</param>
    /// <returns>The generated class source.</returns>
    private static string EmitClass(INamedTypeSymbol classSymbol, IReadOnlyList<GeneratedPoint> points)
    {
        var builder = new StringBuilder();
        _ = builder.AppendLine("// <auto-generated />");
        _ = builder.AppendLine("#nullable enable");

        var namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            _ = builder.Append("namespace ").Append(namespaceName).AppendLine(";");
            _ = builder.AppendLine();
        }

        _ = builder
            .Append(GetAccessibility(classSymbol.DeclaredAccessibility))
            .Append(" partial class ")
            .AppendLine(classSymbol.Name);
        _ = builder.AppendLine("{");

        foreach (var point in points)
        {
            EmitProperty(builder, point);
        }

        _ = builder.AppendLine("    public global::System.IDisposable BindGeneratedModbusStreams()");
        _ = builder.AppendLine(MemberOpenBrace);
        _ = builder.AppendLine(
            "        var disposables = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable();");
        _ = builder.AppendLine("        BindGeneratedModbusStreams(disposables);");
        _ = builder.AppendLine("        return disposables;");
        _ = builder.AppendLine(MemberCloseBrace);
        _ = builder.AppendLine();
        _ = builder.AppendLine(
            "    public global::ReactiveUI.Primitives.Disposables.MultipleDisposable " +
            "BindGeneratedModbusStreams(global::ReactiveUI.Primitives.Disposables.MultipleDisposable disposables)");
        _ = builder.AppendLine(MemberOpenBrace);
        _ = builder.AppendLine("        if (disposables is null)");
        _ = builder.AppendLine(MemberBodyOpenBrace);
        _ = builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(disposables));");
        _ = builder.AppendLine(MemberBodyCloseBrace);
        _ = builder.AppendLine();

        foreach (var point in points)
        {
            EmitSubscription(builder, point);
        }

        _ = builder.AppendLine("        return disposables;");
        _ = builder.AppendLine(MemberCloseBrace);

        EmitObserver(builder);

        foreach (var point in points)
        {
            EmitConversion(builder, point);
        }

        _ = builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>Emits the property and companion members for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitProperty(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var fieldName = ToFieldName(propertyName);
        var subjectName = $"{fieldName}Subject";

        EmitBackedProperty(builder, point, propertyName, typeName, fieldName, subjectName);
        EmitObservableMembers(builder, point, propertyName, typeName, subjectName);
        EmitLogicalTagMembers(builder, point, propertyName, typeName);
    }

    /// <summary>Emits a generated property's storage and setter.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    /// <param name="propertyName">The property name.</param>
    /// <param name="typeName">The generated type name.</param>
    /// <param name="fieldName">The backing field name.</param>
    /// <param name="subjectName">The replay subject name.</param>
    private static void EmitBackedProperty(
        StringBuilder builder,
        GeneratedPoint point,
        string propertyName,
        string typeName,
        string fieldName,
        string subjectName)
    {
        _ = builder.AppendLine();
        _ = builder.Append("    private ").Append(typeName).Append(' ').Append(fieldName).AppendLine(" = default!;");
        _ = builder
            .Append("    private readonly global::ReactiveUI.Primitives.Signals.ReplaySignal<")
            .Append(typeName)
            .Append("> ")
            .Append(subjectName)
            .Append(" = new global::ReactiveUI.Primitives.Signals.ReplaySignal<")
            .Append(typeName)
            .AppendLine(">(1);");
        _ = builder.AppendLine();
        _ = builder
            .Append("    ")
            .Append(GetAccessibility(point.Point.PropertySymbol.DeclaredAccessibility))
            .Append(" partial ")
            .Append(typeName)
            .Append(' ')
            .AppendLine(propertyName);
        _ = builder.AppendLine(MemberOpenBrace);
        _ = builder.Append("        get => ").Append(fieldName).AppendLine(";");
        _ = builder.AppendLine("        private set");
        _ = builder.AppendLine(MemberBodyOpenBrace);
        _ = builder
            .Append("            if (global::System.Collections.Generic.EqualityComparer<")
            .Append(typeName)
            .Append(">.Default.Equals(")
            .Append(fieldName)
            .AppendLine(", value))");
        _ = builder.AppendLine("            {");
        _ = builder.AppendLine("                return;");
        _ = builder.AppendLine("            }");
        _ = builder.AppendLine();
        _ = builder.Append("            ").Append(fieldName).AppendLine(" = value;");
        _ = builder.Append("            ").Append(subjectName).AppendLine(".OnNext(value);");
        _ = builder.AppendLine(MemberBodyCloseBrace);
        _ = builder.AppendLine(MemberCloseBrace);
    }

    /// <summary>Emits observable and error members for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    /// <param name="propertyName">The property name.</param>
    /// <param name="typeName">The generated type name.</param>
    /// <param name="subjectName">The replay subject name.</param>
    private static void EmitObservableMembers(
        StringBuilder builder,
        GeneratedPoint point,
        string propertyName,
        string typeName,
        string subjectName)
    {
        _ = builder.AppendLine();
        _ = builder
            .Append("    public global::System.IObservable<")
            .Append(typeName)
            .Append("> ")
            .Append(propertyName)
            .Append("Observable => ")
            .Append(subjectName)
            .AppendLine(";");
        _ = builder
            .Append("    public global::ReactiveUI.Primitives.Async.IObservableAsync<")
            .Append(typeName)
            .Append("> ")
            .Append(propertyName)
            .Append("ObservableAsync => ")
            .Append(point.Point.DeviceOptions.ApiRoot)
            .Append(".ModbusAsyncObservableExtensions.ToAsyncObservable(")
            .Append(subjectName)
            .AppendLine(");");
        _ = builder
            .Append("    public global::System.Exception? ")
            .Append(propertyName)
            .AppendLine("Error { get; private set; }");
    }

    /// <summary>Emits optional logical-tag read and write helpers.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    /// <param name="propertyName">The property name.</param>
    /// <param name="typeName">The generated type name.</param>
    private static void EmitLogicalTagMembers(
        StringBuilder builder,
        GeneratedPoint point,
        string propertyName,
        string typeName)
    {
        if (point.Point.DeviceOptions.TagClientMember is null)
        {
            return;
        }

        var tagName = point.Point.PointOptions.TagName ?? propertyName;
        var literal = SymbolDisplay.FormatLiteral(tagName, true);
        var client = $"this.{point.Point.DeviceOptions.TagClientMember}";
        _ = builder
            .Append("    public global::System.Threading.Tasks.Task<global::IoT.DriverCore.Core.TagOperationResult<")
            .Append(typeName)
            .Append(">> Read")
            .Append(propertyName)
            .Append("Async(global::System.Threading.CancellationToken cancellationToken = default) => ")
            .Append("global::IoT.DriverCore.Core.LogicalTagContractHelpers.ReadAsync<")
            .Append(typeName)
            .Append(">(")
            .Append(client)
            .Append(", ")
            .Append(literal)
            .AppendLine(", cancellationToken);");
        _ = builder
            .Append("    public global::System.Threading.Tasks.Task<global::IoT.DriverCore.Core.TagOperationResult<")
            .Append(typeName)
            .Append(">> Write")
            .Append(propertyName)
            .Append("Async(")
            .Append(typeName)
            .Append(" value, global::System.Threading.CancellationToken cancellationToken = default) => ")
            .Append("global::IoT.DriverCore.Core.LogicalTagContractHelpers.WriteAsync<")
            .Append(typeName)
            .Append(">(")
            .Append(client)
            .Append(", ")
            .Append(literal)
            .AppendLine(", value, cancellationToken);");
    }

    /// <summary>Emits the binding subscription for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitSubscription(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var readMethod = GetReadMethod(point.Point.Kind);
        var count = point.Point.PointOptions.Count == 0 ? point.Type.RegisterCount : point.Point.PointOptions.Count;
        var connectionMember = point.Point.DeviceOptions.ConnectionMember;
        var interval = point.Point.DeviceOptions.DefaultInterval.ToString(
            System.Globalization.CultureInfo.InvariantCulture);
        var resultType = point.Point.Kind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput
            ? "(bool[]? data, global::System.Exception? error)"
            : "(ushort[]? data, global::System.Exception? error)";

        _ = builder
            .Append("        disposables.Add(")
            .Append(point.Point.DeviceOptions.ApiRoot)
            .Append(".Create.")
            .Append(readMethod)
            .Append("(this.")
            .Append(connectionMember)
            .Append(", ");
        if (point.Point.DeviceOptions.MasterKind == "Serial")
        {
            _ = builder.Append("(byte)").Append(point.Point.DeviceOptions.SlaveAddress).Append(", ");
        }

        _ = builder
            .Append(point.Point.Address)
            .Append(", ")
            .Append(count)
            .Append(", ")
            .Append(interval)
            .Append(").Subscribe(new GeneratedModbusObserver<")
            .Append(resultType)
            .AppendLine(">(result =>");
        _ = builder.AppendLine(MemberBodyOpenBrace);
        _ = builder.Append("            ").Append(propertyName).AppendLine("Error = result.error;");
        _ = builder
            .Append("            if (result.error is null && result.data is not null && result.data.Length >= ")
            .Append(count)
            .AppendLine(")");
        _ = builder.AppendLine("            {");
        _ = builder
            .Append("                ")
            .Append(propertyName)
            .Append(" = Convert")
            .Append(propertyName)
            .AppendLine("(result.data);");
        _ = builder.AppendLine("            }");
        _ = builder.AppendLine("        })));");
        _ = builder.AppendLine();
    }

    /// <summary>Emits the observer adapter used by generated subscriptions.</summary>
    /// <param name="builder">The source builder.</param>
    private static void EmitObserver(StringBuilder builder)
    {
        _ = builder.AppendLine();
        _ = builder.AppendLine("    private sealed class GeneratedModbusObserver<T> : global::System.IObserver<T>");
        _ = builder.AppendLine(MemberOpenBrace);
        _ = builder.AppendLine("        private readonly global::System.Action<T> _onNext;");
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public GeneratedModbusObserver(global::System.Action<T> onNext)");
        _ = builder.AppendLine(MemberBodyOpenBrace);
        _ = builder.AppendLine(
            "            _onNext = onNext ?? throw new global::System.ArgumentNullException(nameof(onNext));");
        _ = builder.AppendLine(MemberBodyCloseBrace);
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnCompleted()");
        _ = builder.AppendLine(MemberBodyOpenBrace);
        _ = builder.AppendLine(MemberBodyCloseBrace);
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnError(global::System.Exception error)");
        _ = builder.AppendLine("        {");
        _ = builder.AppendLine(MemberBodyCloseBrace);
        _ = builder.AppendLine();
        _ = builder.AppendLine("        public void OnNext(T value) => _onNext(value);");
        _ = builder.AppendLine(MemberCloseBrace);
    }

    /// <summary>Emits the conversion method for a generated point.</summary>
    /// <param name="builder">The source builder.</param>
    /// <param name="point">The generated point.</param>
    private static void EmitConversion(StringBuilder builder, GeneratedPoint point)
    {
        var propertyName = point.Point.PropertySymbol.Name;
        var typeName = point.Type.TypeName;
        var methodName = point.Point.Kind is ModbusPointKind.Coil or ModbusPointKind.DiscreteInput
            ? "bool[]"
            : "ushort[]";

        _ = builder.AppendLine();
        _ = builder
            .Append("    private static ")
            .Append(typeName)
            .Append(" Convert")
            .Append(propertyName)
            .Append('(')
            .Append(methodName)
            .AppendLine(" data)");
        _ = builder.AppendLine(MemberOpenBrace);
        _ = builder
            .Append("        return ")
            .Append(point.Type.GetConversionExpression("data", point.Point.PointOptions.SwapWords))
            .AppendLine(";");
        _ = builder.AppendLine(MemberCloseBrace);
    }
}
