// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace IoT.DriverCore.ModbusRx.Generators;

/// <summary>Generates Modbus-backed reactive properties and observable streams.</summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class ModbusReactiveStreamGenerator : IIncrementalGenerator
{
    /// <summary>The generated indentation and opening brace for a member.</summary>
    private const string MemberOpenBrace = "    {";

    /// <summary>The generated indentation and closing brace for a member.</summary>
    private const string MemberCloseBrace = "    }";

    /// <summary>The generated indentation and opening brace for a member body.</summary>
    private const string MemberBodyOpenBrace = "        {";

    /// <summary>The generated indentation and closing brace for a member body.</summary>
    private const string MemberBodyCloseBrace = "        }";

    /// <summary>The number of registers occupied by a 32-bit value.</summary>
    private const ushort RegistersPer32BitValue = 2;

    /// <summary>The number of registers occupied by a 64-bit value.</summary>
    private const ushort RegistersPer64BitValue = 4;

    /// <summary>The generated attribute value for a serial master.</summary>
    private const int SerialMasterKindValue = 2;

    /// <summary>Contains the generated attribute declarations consumed by the source generator.</summary>
    private const string AttributeSource = """
// <auto-generated />
#nullable enable
namespace IoT.DriverCore.ModbusRx.Generators
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class ModbusReactiveDeviceAttribute : global::System.Attribute
    {
        public string ConnectionMember { get; set; } = "MasterStream";

        public string? TagClientMember { get; set; }

        public byte SlaveAddress { get; set; } = 1;

        public double DefaultInterval { get; set; } = 1000.0;

        public ModbusReactiveMasterKind MasterKind { get; set; }
    }

    public enum ModbusReactiveMasterKind
    {
        Auto,
        Ip,
        Serial,
    }

    public enum ModbusReactiveDataType
    {
        Auto,
        Bool,
        UInt16,
        Int16,
        UInt32,
        Int32,
        Float32,
        Float64,
    }

    [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal abstract class ModbusReactivePointAttribute : global::System.Attribute
    {
        protected ModbusReactivePointAttribute(ushort address)
        {
            Address = address;
        }

        public ushort Address { get; }

        public ushort Count { get; set; }

        public ModbusReactiveDataType DataType { get; set; }

        public bool SwapWords { get; set; } = true;

        public string? TagName { get; set; }
    }

    internal sealed class HoldingRegisterAttribute : ModbusReactivePointAttribute
    {
        public HoldingRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class InputRegisterAttribute : ModbusReactivePointAttribute
    {
        public InputRegisterAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class CoilAttribute : ModbusReactivePointAttribute
    {
        public CoilAttribute(ushort address)
            : base(address)
        {
        }
    }

    internal sealed class DiscreteInputAttribute : ModbusReactivePointAttribute
    {
        public DiscreteInputAttribute(ushort address)
            : base(address)
        {
        }
    }
}
""";

    /// <summary>Diagnostic reported when a reactive device class is not partial.</summary>
    private static readonly DiagnosticDescriptor ClassMustBePartial = new(
        "MBRXGEN001",
        "Reactive Modbus device must be partial",
        "Class '{0}' must be partial to receive generated Modbus stream members",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Diagnostic reported when a reactive Modbus property is not partial.</summary>
    private static readonly DiagnosticDescriptor PropertyMustBePartial = new(
        "MBRXGEN002",
        "Reactive Modbus property must be partial",
        "Property '{0}' must be partial so the generator can implement it",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Diagnostic reported when a reactive Modbus property type cannot be converted.</summary>
    private static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
        "MBRXGEN003",
        "Unsupported Modbus property type",
        "Property '{0}' has unsupported type '{1}' for {2}",
        "ModbusRx.Generators",
        DiagnosticSeverity.Error,
        true);

    /// <summary>Identifies the Modbus data source used by a generated reactive point.</summary>
    private enum ModbusPointKind
    {
        /// <summary>No supported Modbus point attribute was found.</summary>
        None,

        /// <summary>A holding register point.</summary>
        HoldingRegister,

        /// <summary>An input register point.</summary>
        InputRegister,

        /// <summary>A coil point.</summary>
        Coil,

        /// <summary>A discrete input point.</summary>
        DiscreteInput,
    }

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource("ModbusReactiveAttributes.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var points = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is PropertyDeclarationSyntax property && property.AttributeLists.Count > 0,
                static (syntaxContext, _) => CreatePoint(syntaxContext))
            .Where(static point => point is not null)
            .Collect();

        context.RegisterSourceOutput(
            points,
            static (sourceContext, collectedPoints) => Execute(sourceContext, collectedPoints));
    }

    /// <summary>Creates a Modbus point model from a property syntax context.</summary>
    /// <param name="context">The generator syntax context.</param>
    /// <returns>The point model when the property is decorated with a Modbus point attribute.</returns>
    private static ModbusPoint? CreatePoint(in GeneratorSyntaxContext context)
    {
        var propertySyntax = (PropertyDeclarationSyntax)context.Node;
        var propertySymbol = context.SemanticModel.GetDeclaredSymbol(propertySyntax);
        if (propertySymbol is null || propertySymbol.ContainingType is null)
        {
            return null;
        }

        var pointAttribute = FindPointAttribute(propertySymbol);
        if (pointAttribute.Attribute is null)
        {
            return null;
        }

        var deviceAttribute = FindDeviceAttribute(propertySymbol.ContainingType);
        if (deviceAttribute is null)
        {
            return null;
        }

        var device = DeviceOptions.From(deviceAttribute);
        device = device.WithApiRoot(ResolveApiRoot(propertySymbol.ContainingType, device.ConnectionMember));
        return new ModbusPoint(
            propertySymbol,
            propertySyntax,
            propertySymbol.ContainingType,
            pointAttribute.Kind,
            GetPointAddress(pointAttribute.Attribute),
            device,
            PointOptions.From(pointAttribute.Attribute));
    }

    /// <summary>Finds the first supported point attribute on a property.</summary>
    /// <param name="propertySymbol">The property symbol.</param>
    /// <returns>The point attribute and kind when one is present.</returns>
    private static (AttributeData? Attribute, ModbusPointKind Kind) FindPointAttribute(IPropertySymbol propertySymbol)
    {
        foreach (var attribute in propertySymbol.GetAttributes())
        {
            var kind = GetPointKind(attribute.AttributeClass);
            if (kind == ModbusPointKind.None)
            {
                continue;
            }

            return (attribute, kind);
        }

        return (null, ModbusPointKind.None);
    }

    /// <summary>Finds the generated device attribute on a class.</summary>
    /// <param name="classSymbol">The class symbol.</param>
    /// <returns>The device attribute when present.</returns>
    private static AttributeData? FindDeviceAttribute(INamedTypeSymbol classSymbol)
    {
        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (IsNamed(attribute.AttributeClass, "ModbusReactiveDeviceAttribute"))
            {
                return attribute;
            }
        }

        return null;
    }

    /// <summary>Gets the point address from the point attribute constructor.</summary>
    /// <param name="attribute">The point attribute.</param>
    /// <returns>The configured Modbus address.</returns>
    private static ushort GetPointAddress(AttributeData attribute) =>
        attribute.ConstructorArguments.Length > 0 &&
        attribute.ConstructorArguments[0].Value is ushort typedAddress
            ? typedAddress
            : (ushort)0;

    /// <summary>Emits source for each reactive Modbus device class represented by the collected points.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="points">The collected Modbus points.</param>
    private static void Execute(in SourceProductionContext context, in ImmutableArray<ModbusPoint?> points)
    {
        foreach (var group in GroupPointsByClass(points))
        {
            if (!TryGetClassSyntax(context, group.Key, group.Value[0], out _))
            {
                continue;
            }

            var validPoints = GetValidPoints(context, group.Value);
            if (validPoints.Count == 0)
            {
                continue;
            }

            var source = EmitClass(group.Key, validPoints);
            var hintName = group.Key
                .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .Replace("global::", string.Empty)
                .Replace('.', '_');
            context.AddSource(
                $"{hintName}.ModbusReactive.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    /// <summary>Groups Modbus points by their containing class.</summary>
    /// <param name="points">The points to group.</param>
    /// <returns>A dictionary keyed by containing class symbol.</returns>
    private static Dictionary<INamedTypeSymbol, List<ModbusPoint>> GroupPointsByClass(
        in ImmutableArray<ModbusPoint?> points)
    {
        var groupedPoints = new Dictionary<INamedTypeSymbol, List<ModbusPoint>>(SymbolEqualityComparer.Default);
        foreach (var candidate in points)
        {
            if (candidate is not ModbusPoint point)
            {
                continue;
            }

            if (!groupedPoints.TryGetValue(point.ClassSymbol, out var classPoints))
            {
                classPoints = [];
                groupedPoints.Add(point.ClassSymbol, classPoints);
            }

            classPoints.Add(point);
        }

        return groupedPoints;
    }

    /// <summary>Attempts to resolve and validate the declaration syntax for a generated class.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="classSymbol">The class symbol.</param>
    /// <param name="firstPoint">The first point declared by the class.</param>
    /// <param name="classSyntax">The resolved class declaration syntax.</param>
    /// <returns>True when the class syntax is available and partial.</returns>
    private static bool TryGetClassSyntax(
        in SourceProductionContext context,
        INamedTypeSymbol classSymbol,
        ModbusPoint firstPoint,
        out ClassDeclarationSyntax? classSyntax)
    {
        classSyntax = firstPoint.PropertySyntax.FirstAncestorOrSelf<ClassDeclarationSyntax>();
        if (classSyntax is null)
        {
            return false;
        }

        if (HasPartialModifier(classSyntax.Modifiers))
        {
            return true;
        }

        context.ReportDiagnostic(
            Diagnostic.Create(ClassMustBePartial, classSyntax.Identifier.GetLocation(), classSymbol.Name));
        return false;
    }

    /// <summary>Creates generated point models for points that pass syntax and type validation.</summary>
    /// <param name="context">The source production context.</param>
    /// <param name="points">The candidate points for one class.</param>
    /// <returns>The generated point models.</returns>
    private static List<GeneratedPoint> GetValidPoints(
        in SourceProductionContext context,
        IReadOnlyList<ModbusPoint> points)
    {
        var validPoints = new List<GeneratedPoint>();
        foreach (var point in points)
        {
            if (!HasPartialModifier(point.PropertySyntax.Modifiers))
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        PropertyMustBePartial,
                        point.PropertySyntax.Identifier.GetLocation(),
                        point.PropertySymbol.Name));
                continue;
            }

            var typeInfo = ModbusTypeInfo.Create(point.PropertySymbol.Type, point.Kind, point.DeviceOptions.ApiRoot);
            if (typeInfo is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedPropertyType,
                    point.PropertySyntax.Type.GetLocation(),
                    point.PropertySymbol.Name,
                    point.PropertySymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    point.Kind));
                continue;
            }

            validPoints.Add(new GeneratedPoint(point, typeInfo));
        }

        return validPoints;
    }

    /// <summary>Determines whether a modifier list contains the partial keyword.</summary>
    /// <param name="modifiers">The syntax modifiers.</param>
    /// <returns>True when the list contains a partial modifier.</returns>
    private static bool HasPartialModifier(in SyntaxTokenList modifiers)
    {
        foreach (var modifier in modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>Gets the Create API read method name for a Modbus point kind.</summary>
    /// <param name="kind">The point kind.</param>
    /// <returns>The read method name.</returns>
    private static string GetReadMethod(ModbusPointKind kind) =>
        kind switch
        {
            ModbusPointKind.HoldingRegister => "ReadHoldingRegisters",
            ModbusPointKind.InputRegister => "ReadInputRegisters",
            ModbusPointKind.Coil => "ReadCoils",
            ModbusPointKind.DiscreteInput => "ReadInputs",
            _ => throw new InvalidOperationException("Unsupported point kind."),
        };

    /// <summary>Gets a source accessibility keyword for a Roslyn accessibility value.</summary>
    /// <param name="accessibility">The Roslyn accessibility value.</param>
    /// <returns>The generated source accessibility keyword.</returns>
    private static string GetAccessibility(Accessibility accessibility) =>
        accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal",
        };

    /// <summary>Gets the Modbus point kind represented by an attribute type.</summary>
    /// <param name="attributeType">The attribute type symbol.</param>
    /// <returns>The matching point kind, or none when the attribute is unsupported.</returns>
    private static ModbusPointKind GetPointKind(INamedTypeSymbol? attributeType)
    {
        if (IsNamed(attributeType, "HoldingRegisterAttribute"))
        {
            return ModbusPointKind.HoldingRegister;
        }

        if (IsNamed(attributeType, "InputRegisterAttribute"))
        {
            return ModbusPointKind.InputRegister;
        }

        if (IsNamed(attributeType, "CoilAttribute"))
        {
            return ModbusPointKind.Coil;
        }

        return IsNamed(attributeType, "DiscreteInputAttribute") ? ModbusPointKind.DiscreteInput : ModbusPointKind.None;
    }

    /// <summary>Determines whether a symbol has the expected generated attribute name.</summary>
    /// <param name="symbol">The symbol to check.</param>
    /// <param name="metadataName">The expected metadata name.</param>
    /// <returns>True when the symbol matches the generated attribute namespace and name.</returns>
    private static bool IsNamed(INamedTypeSymbol? symbol, string metadataName) =>
        symbol?.Name == metadataName
        && symbol.ContainingNamespace.ToDisplayString() == "IoT.DriverCore.ModbusRx.Generators";

    /// <summary>Resolves the generated API root namespace from the configured connection member.</summary>
    /// <param name="classSymbol">The class symbol that declares the connection member.</param>
    /// <param name="connectionMember">The configured connection member name.</param>
    /// <returns>The generated API root namespace.</returns>
    private static string ResolveApiRoot(INamedTypeSymbol classSymbol, string connectionMember)
    {
        ITypeSymbol? memberType = null;
        foreach (var member in classSymbol.GetMembers(connectionMember))
        {
            memberType = member switch
            {
                IPropertySymbol property => property.Type,
                IFieldSymbol field => field.Type,
                _ => null,
            };

            if (memberType is not null)
            {
                break;
            }
        }

        var typeName = memberType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? string.Empty;
        return typeName.Contains("global::IoT.DriverCore.ModbusRx.Reactive.Device.", StringComparison.Ordinal)
            ? "global::IoT.DriverCore.ModbusRx.Reactive"
            : "global::IoT.DriverCore.ModbusRx";
    }

    /// <summary>Creates the generated backing field name for a property.</summary>
    /// <param name="propertyName">The property name.</param>
    /// <returns>The generated backing field name.</returns>
    private static string ToFieldName(string propertyName) =>
        $"_{char.ToLowerInvariant(propertyName[0])}{propertyName.Remove(0, 1)}";
}
