// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace OmronPlcRx.SourceGenerators;

/// <summary>Contains source-emission helpers for PLC tag bindings.</summary>
public sealed partial class PlcTagSourceGenerator
{
    /// <summary>Generated prefix for typed logical-tag operation results.</summary>
    private const string ResultType = "global::CP.IoT.Core.TagOperationResult<";

    /// <summary>Generated suffix for opening an indented block.</summary>
    private const string BlockOpen = "    {";

    /// <summary>Generated suffix for closing an indented block.</summary>
    private const string BlockClose = "    }";

    /// <summary>Generated indentation and keyword for a return statement.</summary>
    private const string ReturnIndent = "        return ";

    /// <summary>Generated typed logical-tag key type.</summary>
    private const string LogicalTagKeyType = "global::CP.IoT.Core.LogicalTagKey";

    /// <summary>Generated value parameter and expression name.</summary>
    private const string GeneratedValueName = "value";

    /// <summary>Generates source for one target type.</summary>
    /// <param name="type">Target type.</param>
    /// <param name="specs">Tags to generate.</param>
    /// <returns>The generated source text.</returns>
    private static string GenerateSource(INamedTypeSymbol type, IReadOnlyList<TagSpec> specs)
    {
        var builder = new StringBuilder();
        Line(builder, "// <auto-generated />");
        Line(builder, "#nullable enable");
        Line(builder, "using System;");
        Line(builder, "using CP.IoT.Core;");
        Line(builder, "using ReactiveUI.Primitives;");
        Line(builder, "#if NET8_0_OR_GREATER");
        Line(builder, "using ReactiveUI.Primitives.Async;");
        Line(builder, "#endif");
        Line(builder);

        var namespaceName = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();
        var rootIndent = string.Empty;
        if (namespaceName is not null)
        {
            Line(builder, $"namespace {namespaceName}");
            Line(builder, "{");
            rootIndent = "    ";
        }

        var memberIndent = $"{rootIndent}    ";
        Line(builder, $"{rootIndent}{Accessibility(type)} partial class {type.Name}");
        Line(builder, $"{rootIndent}{{");
        EmitClient(builder, memberIndent, LogicalClientType(type));
        foreach (var spec in specs)
        {
            EmitProperty(builder, memberIndent, spec, AsyncBridgeType(type));
        }

        EmitRegister(builder, memberIndent, specs, FacadeType(type), LogicalClientType(type));
        EmitBind(builder, memberIndent, specs, FacadeType(type), LogicalTagKeyType);
        foreach (var spec in specs)
        {
            EmitRead(
                builder,
                memberIndent,
                spec,
                LogicalTagKeyType);
            if (spec.Writable)
            {
                EmitWrite(
                    builder,
                    memberIndent,
                    spec,
                    FacadeType(type),
                    LogicalTagKeyType);
            }
        }

        Line(builder, $"{rootIndent}}}");
        if (namespaceName is not null)
        {
            Line(builder, "}");
        }

        return builder.ToString();
    }

    /// <summary>Emits the composed logical-client storage.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="clientType">Logical client type.</param>
    private static void EmitClient(StringBuilder builder, string indent, string clientType)
    {
        Line(builder, $"{indent}private {clientType}? _omronLogicalTagClient;");
        Line(builder);
        Line(builder, $"{indent}private {clientType} GetOmronLogicalTagClient() =>");
        Line(builder, $"{indent}    _omronLogicalTagClient ??");
        Line(builder, $"{indent}    throw new global::System.InvalidOperationException(");
        Line(
            builder,
            $"{indent}        \"RegisterPlcTags or BindPlcTags must be called first.\");");
        Line(builder);
    }

    /// <summary>Emits a property, streams, and notification callback.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="bridgeType">Observable-to-async bridge type.</param>
    private static void EmitProperty(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string bridgeType)
    {
        var subject = $"_{char.ToLowerInvariant(spec.PropertyName[0])}{spec.PropertyName.Substring(1)}PlcSubject";
        EmitPropertySubject(builder, indent, spec, subject);

        if (spec.GeneratesProperty)
        {
            EmitGeneratedProperty(builder, indent, spec);
        }

        EmitPropertyStreams(builder, indent, spec, bridgeType);
    }

    /// <summary>Emits a backing signal and accessor.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="subject">Backing signal field name.</param>
    private static void EmitPropertySubject(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string subject)
    {
        Line(builder, $"{indent}private global::ReactiveUI.Primitives.Signals.BehaviorSignal<");
        Line(builder, $"{indent}    {spec.PropertyType}>? {subject};");
        Line(builder, $"{indent}private global::ReactiveUI.Primitives.Signals.BehaviorSignal<");
        Line(
            builder,
            $"{indent}    {spec.PropertyType}> {spec.PropertyName}Subject =>");
        Line(builder, $"{indent}    {subject} ??= new({spec.PropertyName});");
        Line(builder);
    }

    /// <summary>Emits a generated tag property.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    private static void EmitGeneratedProperty(StringBuilder builder, string indent, TagSpec spec)
    {
        EmitGeneratedSummary(
            builder,
            indent,
            $"Gets the current {spec.PropertyName} PLC tag value.");
        Line(builder, $"{indent}public {spec.PropertyType} {spec.PropertyName}");
        Line(builder, $"{indent}{{");
        Line(builder, $"{indent}    get => {spec.MemberName};");
        Line(builder, $"{indent}    private set");
        Line(builder, string.Concat(indent, BlockOpen));
        Line(
            builder,
            $"{indent}        if (!global::System.Collections.Generic.EqualityComparer<");
        Line(builder, $"{indent}            {spec.PropertyType}>.Default.Equals(");
        Line(builder, $"{indent}                {spec.MemberName}, value))");
        Line(builder, $"{indent}        {{");
        Line(builder, $"{indent}            {spec.MemberName} = value;");
        Line(builder, $"{indent}            {spec.PropertyName}Subject.OnNext(value);");
        Line(builder, $"{indent}            On{spec.PropertyName}Received(value);");
        Line(builder, $"{indent}        }}");
        Line(builder, string.Concat(indent, BlockClose));
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits observable streams and the notification callback.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="bridgeType">Observable-to-async bridge type.</param>
    private static void EmitPropertyStreams(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string bridgeType)
    {
        EmitGeneratedSummary(
            builder,
            indent,
            $"Gets observable changes for the {spec.PropertyName} PLC tag.");
        Line(
            builder,
            $"{indent}public global::System.IObservable<{spec.PropertyType}> "
                + $"{spec.PropertyName}Observable => {spec.PropertyName}Subject;");
        Line(builder);
        Line(builder, "#if NET8_0_OR_GREATER");
        EmitGeneratedSummary(
            builder,
            indent,
            $"Gets asynchronous observable changes for the {spec.PropertyName} PLC tag.");
        Line(builder, $"{indent}public global::ReactiveUI.Primitives.Async.IObservableAsync<");
        Line(
            builder,
            $"{indent}    {spec.PropertyType}> {spec.PropertyName}ObservableAsync =>");
        Line(
            builder,
            $"{indent}    {bridgeType}.ToAsyncObservable({spec.PropertyName}Observable);");
        Line(builder, "#endif");
        Line(builder);
        Line(
            builder,
            $"{indent}partial void On{spec.PropertyName}Received({spec.PropertyType} value);");
        Line(builder);
    }

    /// <summary>Emits the tag registration method.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="specs">Tags to register.</param>
    /// <param name="facadeType">PLC facade type.</param>
    /// <param name="clientType">Logical client type.</param>
    private static void EmitRegister(
        StringBuilder builder,
        string indent,
        IEnumerable<TagSpec> specs,
        string facadeType,
        string clientType)
    {
        EmitGeneratedSummary(builder, indent, "Registers the generated PLC tags.");
        EmitGeneratedParameter(builder, indent, "plc", "PLC facade used for tag operations.");
        Line(builder, $"{indent}public void RegisterPlcTags({facadeType} plc)");
        Line(builder, $"{indent}{{");
        EmitNullGuard(builder, indent, "plc");
        Line(builder, $"{indent}    _omronLogicalTagClient?.Dispose();");
        Line(builder, $"{indent}    var client = new {clientType}(plc);");
        foreach (var spec in specs)
        {
            var target = spec.Register ? "client.RegisterTag" : "client.Catalog.Upsert";
            var tagName = Escape(spec.TagName);
            var address = Escape(spec.Address);
            var typeExpression = $"typeof({spec.TagType})";
            var accessMode = spec.Writable ? "ReadWrite" : "Read";
            Line(builder, $"{indent}    {target}(new global::CP.IoT.Core.LogicalTag(");
            Line(
                builder,
                $"{indent}        \"{tagName}\", \"{address}\", {typeExpression}.FullName ??");
            Line(
                builder,
                $"{indent}        {typeExpression}.Name, new global::CP.IoT.Core.LogicalTagOptions {{");
            Line(
                builder,
                $"{indent}            AccessMode = global::CP.IoT.Core.LogicalTagAccessMode.{accessMode},");
            Line(builder, $"{indent}        }}));");
        }

        Line(builder, $"{indent}    _omronLogicalTagClient = client;");
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits the observable binding method.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="specs">Tags to bind.</param>
    /// <param name="facadeType">PLC facade type.</param>
    /// <param name="tagKeyType">Logical tag key type.</param>
    private static void EmitBind(
        StringBuilder builder,
        string indent,
        IEnumerable<TagSpec> specs,
        string facadeType,
        string tagKeyType)
    {
        EmitGeneratedSummary(builder, indent, "Registers and binds the generated PLC tag streams.");
        EmitGeneratedParameter(builder, indent, "plc", "PLC facade used for tag operations.");
        EmitGeneratedReturns(builder, indent, "A disposable that releases all generated tag bindings.");
        Line(
            builder,
            $"{indent}public global::System.IDisposable BindPlcTags({facadeType} plc)");
        Line(builder, $"{indent}{{");
        EmitNullGuard(builder, indent, "plc");
        Line(builder, $"{indent}    RegisterPlcTags(plc);");
        Line(
            builder,
            $"{indent}    var items = new global::ReactiveUI.Primitives.Disposables.MultipleDisposable();");
        foreach (var spec in specs)
        {
            if (!spec.Observe)
            {
                continue;
            }

            var logicalTag = $"{tagKeyType}<{spec.TagType}>(\"{Escape(spec.TagName)}\")";
            Line(
                builder,
                $"{indent}    items.Add(plc.Observe(new {logicalTag}).SubscribeSafe(value =>");
            Line(builder, string.Concat(indent, BlockOpen));
            EmitAssignment(builder, $"{indent}        ", spec, GeneratedValueName, true);
            Line(builder, $"{indent}    }}, static exception => throw exception));");
        }

        Line(builder, $"{indent}    return items;");
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits an awaited logical-tag read helper.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="tagKeyType">Logical tag key type.</param>
    private static void EmitRead(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string tagKeyType)
    {
        EmitGeneratedSummary(
            builder,
            indent,
            $"Reads the {spec.PropertyName} PLC tag asynchronously.");
        EmitGeneratedParameter(
            builder,
            indent,
            "cancellationToken",
            "Token used to cancel the read operation.");
        EmitGeneratedReturns(builder, indent, "The typed PLC tag operation result.");
        Line(
            builder,
            $"{indent}public async global::System.Threading.Tasks.Task<{ResultType}{spec.PropertyType}>> "
                + $"Read{spec.PropertyName}Async(");
        Line(
            builder,
            $"{indent}    global::System.Threading.CancellationToken cancellationToken)");
        Line(builder, $"{indent}{{");
        Line(
            builder,
            $"{indent}    var result = await GetOmronLogicalTagClient().ReadAsync(new "
                + $"{tagKeyType}<{spec.TagType}>(\"{Escape(spec.TagName)}\"),");
        Line(builder, $"{indent}        cancellationToken).ConfigureAwait(false);");
        EmitReadValidation(builder, indent, spec);
        EmitAssignment(builder, $"{indent}    ", spec, "result.Value", false);
        Line(
            builder,
            $"{indent}    return {ResultType}{spec.PropertyType}>.Success({spec.PropertyName});");
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits typed logical-tag read result validation.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    private static void EmitReadValidation(StringBuilder builder, string indent, TagSpec spec)
    {
        Line(builder, $"{indent}    if (!result.Succeeded)");
        Line(builder, string.Concat(indent, BlockOpen));
        Line(
            builder,
            $"{indent}{ReturnIndent}{ResultType}{spec.PropertyType}>.Failure(result.Error);");
        Line(builder, string.Concat(indent, BlockClose));
        if (!spec.NeedsNullGuard)
        {
            return;
        }

        Line(builder, $"{indent}    if (result.Value is null)");
        Line(builder, string.Concat(indent, BlockOpen));
        Line(builder, $"{indent}{ReturnIndent}{ResultType}{spec.PropertyType}>.Failure(");
        Line(
            builder,
            $"{indent}            \"PLC tag '{Escape(spec.TagName)}' returned null.\");");
        Line(builder, string.Concat(indent, BlockClose));
    }

    /// <summary>Emits legacy and awaited write helpers.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="facadeType">PLC facade type.</param>
    /// <param name="tagKeyType">Logical tag key type.</param>
    private static void EmitWrite(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string facadeType,
        string tagKeyType)
    {
        EmitLegacyWrite(builder, indent, spec, facadeType, tagKeyType);
        EmitAwaitedWrite(builder, indent, spec, tagKeyType);
    }

    /// <summary>Emits the legacy write helper.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="facadeType">PLC facade type.</param>
    /// <param name="tagKeyType">Logical tag key type.</param>
    private static void EmitLegacyWrite(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string facadeType,
        string tagKeyType)
    {
        EmitGeneratedSummary(builder, indent, $"Writes the {spec.PropertyName} PLC tag.");
        EmitGeneratedParameter(builder, indent, "plc", "PLC facade used for the write operation.");
        EmitGeneratedParameter(builder, indent, GeneratedValueName, "Value to write.");
        Line(
            builder,
            $"{indent}public void Write{spec.PropertyName}({facadeType} plc, {spec.PropertyType} value)");
        Line(builder, $"{indent}{{");
        EmitNullGuard(builder, indent, "plc");
        Line(
            builder,
            $"{indent}    plc.SetValue(new {tagKeyType}<{spec.TagType}>(\"{Escape(spec.TagName)}\"), value);");
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits the awaited write helper.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="tagKeyType">Logical tag key type.</param>
    private static void EmitAwaitedWrite(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string tagKeyType)
    {
        EmitGeneratedSummary(
            builder,
            indent,
            $"Writes the {spec.PropertyName} PLC tag asynchronously.");
        EmitGeneratedParameter(builder, indent, GeneratedValueName, "Value to write.");
        EmitGeneratedParameter(
            builder,
            indent,
            "cancellationToken",
            "Token used to cancel the write operation.");
        EmitGeneratedReturns(builder, indent, "The typed PLC tag operation result.");
        Line(
            builder,
            $"{indent}public async global::System.Threading.Tasks.Task<{ResultType}{spec.PropertyType}>> "
                + $"Write{spec.PropertyName}Async(");
        Line(builder, $"{indent}    {spec.PropertyType} value,");
        Line(
            builder,
            $"{indent}    global::System.Threading.CancellationToken cancellationToken)");
        Line(builder, $"{indent}{{");
        Line(
            builder,
            $"{indent}    var result = await GetOmronLogicalTagClient().WriteAsync(new "
                + $"{tagKeyType}<{spec.TagType}>(\"{Escape(spec.TagName)}\"),");
        Line(builder, $"{indent}        value, cancellationToken).ConfigureAwait(false);");
        Line(builder, $"{indent}    if (!result.Succeeded)");
        Line(builder, string.Concat(indent, BlockOpen));
        Line(
            builder,
            $"{indent}{ReturnIndent}{ResultType}{spec.PropertyType}>.Failure(result.Error);");
        Line(builder, string.Concat(indent, BlockClose));
        EmitAssignment(builder, $"{indent}    ", spec, GeneratedValueName, false);
        Line(
            builder,
            $"{indent}    return {ResultType}{spec.PropertyType}>.Success({spec.PropertyName});");
        Line(builder, $"{indent}}}");
        Line(builder);
    }

    /// <summary>Emits an XML documentation summary for a generated member.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="summary">Summary text.</param>
    private static void EmitGeneratedSummary(StringBuilder builder, string indent, string summary)
    {
        Line(builder, $"{indent}/// <summary>{summary}</summary>");
    }

    /// <summary>Emits XML documentation for a generated parameter.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="name">Parameter name.</param>
    /// <param name="description">Parameter description.</param>
    private static void EmitGeneratedParameter(
        StringBuilder builder,
        string indent,
        string name,
        string description)
    {
        Line(builder, $"{indent}/// <param name=\"{name}\">{description}</param>");
    }

    /// <summary>Emits XML documentation for a generated return value.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="description">Return-value description.</param>
    private static void EmitGeneratedReturns(StringBuilder builder, string indent, string description)
    {
        Line(builder, $"{indent}/// <returns>{description}</returns>");
    }

    /// <summary>Emits a tag value assignment and notifications.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Current indentation.</param>
    /// <param name="spec">Tag generation model.</param>
    /// <param name="value">Generated value expression.</param>
    /// <param name="guardNull">Whether a null value should return without assignment.</param>
    private static void EmitAssignment(
        StringBuilder builder,
        string indent,
        TagSpec spec,
        string value,
        bool guardNull)
    {
        if (guardNull && spec.NeedsNullGuard)
        {
            Line(builder, $"{indent}if ({value} is null)");
            Line(builder, $"{indent}{{");
            Line(builder, $"{indent}    return;");
            Line(builder, $"{indent}}}");
        }

        Line(builder, $"{indent}{spec.PropertyName} = {value};");
        if (spec.GeneratesProperty)
        {
            return;
        }

        Line(builder, $"{indent}{spec.PropertyName}Subject.OnNext({spec.PropertyName});");
        Line(builder, $"{indent}On{spec.PropertyName}Received({spec.PropertyName});");
    }

    /// <summary>Emits an argument-null guard.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="indent">Member indentation.</param>
    /// <param name="name">Argument name.</param>
    private static void EmitNullGuard(StringBuilder builder, string indent, string name)
    {
        Line(builder, $"{indent}    if ({name} is null)");
        Line(builder, string.Concat(indent, BlockOpen));
        Line(
            builder,
            $"{indent}        throw new global::System.ArgumentNullException(nameof({name}));");
        Line(builder, string.Concat(indent, BlockClose));
    }

    /// <summary>Gets the generated type accessibility.</summary>
    /// <param name="type">Target type.</param>
    /// <returns>The C# accessibility keyword.</returns>
    private static string Accessibility(INamedTypeSymbol type) =>
        type.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public
            ? "public"
            : "internal";

    /// <summary>Gets the PLC facade type for a target.</summary>
    /// <param name="type">Target type.</param>
    /// <returns>The fully qualified facade type.</returns>
    private static string FacadeType(INamedTypeSymbol type) =>
        IsReactive(type)
            ? "global::OmronPlcRx.Reactive.IOmronPlcRx"
            : "global::OmronPlcRx.IOmronPlcRx";

    /// <summary>Gets the logical client type for a target.</summary>
    /// <param name="type">Target type.</param>
    /// <returns>The fully qualified logical client type.</returns>
    private static string LogicalClientType(INamedTypeSymbol type) =>
        IsReactive(type)
            ? "global::OmronPlcRx.Reactive.OmronLogicalTagClient"
            : "global::OmronPlcRx.OmronLogicalTagClient";

    /// <summary>Gets the observable bridge type for a target.</summary>
    /// <param name="type">Target type.</param>
    /// <returns>The fully qualified bridge type.</returns>
    private static string AsyncBridgeType(INamedTypeSymbol type) =>
        IsReactive(type)
            ? "global::CP.IO.Ports.Reactive.ObservableAsyncBridgeExtensions"
            : "global::CP.IO.Ports.ObservableAsyncBridgeExtensions";

    /// <summary>Determines whether a target belongs to the reactive namespace.</summary>
    /// <param name="type">Target type.</param>
    /// <returns>True for the reactive shim namespace; otherwise false.</returns>
    private static bool IsReactive(INamedTypeSymbol type)
    {
        var value = type.ContainingNamespace.ToDisplayString();
        return value == "OmronPlcRx.Reactive"
            || value.StartsWith("OmronPlcRx.Reactive.", StringComparison.Ordinal);
    }

    /// <summary>Escapes a string for a generated literal.</summary>
    /// <param name="value">Value to escape.</param>
    /// <returns>The escaped value.</returns>
    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>Appends a generated source line.</summary>
    /// <param name="builder">Generated source builder.</param>
    /// <param name="value">Line content.</param>
    private static void Line(StringBuilder builder, string value) => _ = builder.AppendLine(value);

    /// <summary>Appends an empty generated source line.</summary>
    /// <param name="builder">Generated source builder.</param>
    private static void Line(StringBuilder builder) => _ = builder.AppendLine();
}
