// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace IoT.DriverCore.TwinCATRx.SourceGenerators;

/// <summary>Generates TwinCAT reactive stream binding members.</summary>
public sealed partial class TwinCatReactiveStreamGenerator : IIncrementalGenerator
{
    /// <summary>Stores the runtime and core helper type name.</summary>
    private const string TwinCatRxExtensionsTypeName = "TwinCatRxExtensions";

    /// <summary>Generates the legacy reactive stream binding source.</summary>
    /// <param name="spec">The target class specification.</param>
    /// <param name="properties">The reactive properties to generate.</param>
    /// <returns>The generated C# source.</returns>
    private static string GenerateLegacy(LegacyStreamSpec spec, IReadOnlyList<LegacyReactivePropertySpec> properties)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("using System;")
            .AppendLine(Net5OrGreaterDirective)
            .AppendLine("using System.Diagnostics.CodeAnalysis;")
            .AppendLine(EndIfDirective)
            .AppendLine("using ReactiveUI.Primitives.Disposables;")
            .AppendLine();
        AppendUsingAlias(sb, "TwinCatRxClientContract", GetLibraryNamespace(spec.Surface), "IRxTcAdsClient");
        AppendUsingAlias(sb, "TwinCatRxLogicalTags", GetLibraryNamespace(spec.Surface), "TwinCatLogicalTagClient");
        AppendUsingAlias(
            sb,
            "TwinCatRxObservableBridge",
            GetLibraryNamespace(spec.Surface),
            "ObservableBridgeExtensions");
        AppendUsingAlias(sb, "TwinCatRxApiExtensions", GetLibraryNamespace(spec.Surface), TwinCatRxExtensionsTypeName);
        _ = sb.AppendLine();

        AppendNamespace(sb, spec.Namespace);

        _ = sb.Append(spec.Accessibility).Append(" partial class ").AppendLine(spec.ClassName)
            .AppendLine("{")
            .AppendLine("    private TwinCatRxLogicalTags? _twinCatRxLogicalTags;")
            .AppendLine("    public TwinCatRxLogicalTags? TwinCatRxLogicalTags => _twinCatRxLogicalTags;")
            .AppendLine();

        AppendLegacyProperties(sb, properties);

        _ = sb.AppendLine(Net5OrGreaterDirective)
            .AppendLine("    [RequiresUnreferencedCode(\"Logical TwinCAT tags may route through " +
                "HashTableRx structure materialization.\")]")
            .AppendLine(EndIfDirective)
            .AppendLine("    public IDisposable BindTwinCatRx(TwinCatRxClientContract client)")
            .AppendLine(ClassOpenBrace)
            .AppendLine("        if (client == null)")
            .AppendLine(BlockOpenBrace)
            .AppendLine("            throw new ArgumentNullException(nameof(client));")
            .AppendLine(BlockCloseBrace)
            .AppendLine()
            .AppendLine("        var subscriptions = new MultipleDisposable();")
            .AppendLine("        var logicalTags = new TwinCatRxLogicalTags(client);")
            .AppendLine("        _twinCatRxLogicalTags = logicalTags;")
            .AppendLine("        subscriptions.Add(logicalTags);")
            .AppendLine("        subscriptions.Add(Scope.Create(() =>")
            .AppendLine("        {")
            .AppendLine("            if (ReferenceEquals(_twinCatRxLogicalTags, logicalTags))")
            .AppendLine(NestedBlockOpenBrace)
            .AppendLine("                _twinCatRxLogicalTags = null;")
            .AppendLine(NestedBlockCloseBrace)
            .AppendLine("        }));");

        AppendLegacyBindings(sb, properties);

        _ = sb.AppendLine("        return subscriptions;")
            .AppendLine(ClassCloseBrace)
            .AppendLine()
            .AppendLine("    private TwinCatRxLogicalTags RequireTwinCatRxLogicalTags() =>")
            .AppendLine("        _twinCatRxLogicalTags ?? throw new InvalidOperationException(" +
                "\"The generated TwinCATRx class is not bound to a PLC client.\");")
            .AppendLine("}");

        return sb.ToString();
    }

    /// <summary>Appends the property surface for legacy generated streams.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="properties">The legacy property specifications.</param>
    private static void AppendLegacyProperties(
        StringBuilder sb,
        IReadOnlyList<LegacyReactivePropertySpec> properties)
    {
        foreach (var property in properties)
        {
            var fieldName = ToCamel(property.PropertyName);
            _ = sb.Append("    private readonly global::ReactiveUI.Primitives.Signals.BehaviorSignal<")
                .Append(property.TypeName).Append("?> _").Append(fieldName).AppendLine("Subject = new(default);")
                .Append("    private ").Append(property.TypeName).Append("? _").Append(fieldName).AppendLine(";")
                .Append("    public ").Append(property.TypeName).Append("? ").AppendLine(property.PropertyName)
                .AppendLine(ClassOpenBrace)
                .Append("        get => _").Append(fieldName).AppendLine(";")
                .AppendLine("        private set")
                .AppendLine(BlockOpenBrace)
                .Append("            _").Append(fieldName).AppendLine(" = value;")
                .Append("            _").Append(fieldName).AppendLine("Subject.OnNext(value);")
                .AppendLine(BlockCloseBrace)
                .AppendLine(ClassCloseBrace)
                .Append("    public IObservable<").Append(property.TypeName).Append("?> ")
                .Append(property.ObservableName).Append(" => _").Append(fieldName).AppendLine("Subject;")
                .Append("    public global::ReactiveUI.Primitives.Async.IObservableAsync<")
                .Append(property.TypeName).Append("?> ").Append(property.ObservableName)
                .Append("Async => TwinCatRxObservableBridge.ToAsyncObservable(")
                .Append(property.ObservableName).AppendLine(");");
            AppendLegacyLogicalTagMembers(sb, property);
        }
    }

    /// <summary>Appends one legacy logical-tag declaration and its asynchronous methods.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="property">The legacy property specification.</param>
    private static void AppendLegacyLogicalTagMembers(StringBuilder sb, LegacyReactivePropertySpec property)
    {
        _ = sb.Append("    public global::IoT.DriverCore.Core.LogicalTag ").Append(property.PropertyName)
            .Append("Tag => new global::IoT.DriverCore.Core.LogicalTag(nameof(").Append(property.PropertyName)
            .Append("), \"").Append(Escape(property.Variable)).Append("\", typeof(").Append(property.TypeName)
            .Append(").FullName ?? typeof(").Append(property.TypeName).AppendLine(").Name);")
            .Append(AsyncResultMethodPrefix).Append(property.TypeName).Append(">> Read")
            .Append(property.PropertyName)
            .AppendLine("Async(System.Threading.CancellationToken cancellationToken = default) =>")
            .Append("        ");
        _ = AppendTypedLogicalTagOperation(sb, "ReadAsync", property.TypeName, property.PropertyName)
            .AppendLine(", cancellationToken);")
            .Append(AsyncResultMethodPrefix).Append(property.TypeName).Append(">> Write")
            .Append(property.PropertyName).Append("Async(").Append(property.TypeName)
            .AppendLine(" value, System.Threading.CancellationToken cancellationToken = default) =>")
            .Append("        ");
        _ = AppendTypedLogicalTagOperation(sb, "WriteAsync", property.TypeName, property.PropertyName)
            .AppendLine(", value, cancellationToken);")
            .AppendLine();
    }

    /// <summary>Appends legacy logical-tag registrations and event bindings.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="properties">The legacy property specifications.</param>
    private static void AppendLegacyBindings(
        StringBuilder sb,
        IReadOnlyList<LegacyReactivePropertySpec> properties)
    {
        foreach (var property in properties)
        {
            _ = sb.Append("        logicalTags.RegisterTag(").Append(property.PropertyName).AppendLine("Tag);")
                .Append("        subscriptions.Add(TwinCatRxObservableBridge.SubscribeTo(")
                .Append("TwinCatRxApiExtensions.Observe<").Append(property.TypeName).Append(">(client, \"")
                .Append(Escape(property.Variable)).Append('"');
            if (property.Id is not null)
            {
                _ = sb.Append(", \"").Append(Escape(property.Id)).Append('"');
            }

            _ = sb.Append(", static value => value is ").Append(property.TypeName)
                .Append(" typedValue ? typedValue : throw new InvalidCastException(\"")
                .Append(Escape(property.Variable)).Append(" produced an incompatible value.\")), value => ")
                .Append(property.PropertyName).AppendLine(" = value));");
        }
    }

    /// <summary>Generates the PLC connection binding source.</summary>
    /// <param name="spec">The target class specification.</param>
    /// <returns>The generated C# source.</returns>
    private static string GenerateConnection(ConnectionSpec spec)
    {
        var sb = new StringBuilder();
        _ = sb.AppendLine("// <auto-generated/>")
            .AppendLine("#nullable enable")
            .AppendLine("using System;")
            .AppendLine(Net5OrGreaterDirective)
            .AppendLine("using System.Diagnostics.CodeAnalysis;")
            .AppendLine(EndIfDirective)
            .Append(UsingDirectivePrefix).Append(GetCollectionsNamespace(spec.Surface)).AppendLine(";")
            .Append(UsingDirectivePrefix).Append(GetCoreNamespace(spec.Surface)).AppendLine(";")
            .AppendLine("using ReactiveUI.Primitives.Disposables;")
            .AppendLine();
        AppendUsingAlias(sb, "TwinCatRxHashTable", GetCollectionsNamespace(spec.Surface), "HashTableRx");
        AppendUsingAlias(
            sb,
            "TwinCatRxHashTableExtensions",
            GetCollectionsNamespace(spec.Surface),
            "HashTableRxExtensions");
        AppendUsingAlias(sb, "TwinCatRxClientContract", GetLibraryNamespace(spec.Surface), "IRxTcAdsClient");
        AppendUsingAlias(sb, "TwinCatRxClient", GetLibraryNamespace(spec.Surface), "RxTcAdsClient");
        AppendUsingAlias(sb, "TwinCatRxLogicalTags", GetLibraryNamespace(spec.Surface), "TwinCatLogicalTagClient");
        AppendUsingAlias(
            sb,
            "TwinCatRxObservableBridge",
            GetLibraryNamespace(spec.Surface),
            "ObservableBridgeExtensions");
        AppendUsingAlias(
            sb,
            "TwinCatRxApiExtensions",
            GetLibraryNamespace(spec.Surface),
            TwinCatRxExtensionsTypeName);
        AppendUsingAlias(
            sb,
            "TwinCatRxCoreExtensions",
            GetCoreNamespace(spec.Surface),
            TwinCatRxExtensionsTypeName);
        AppendUsingAlias(sb, "TwinCatRxSettings", GetCoreNamespace(spec.Surface), "Settings");
        _ = sb.AppendLine();

        AppendNamespace(sb, spec.Namespace);

        _ = sb.Append(spec.Accessibility).Append(" partial class ").AppendLine(spec.ClassName)
            .AppendLine("{")
            .AppendLine("    private TwinCatRxClientContract? _twinCatRxClient;")
            .AppendLine("    private TwinCatRxLogicalTags? _twinCatRxLogicalTags;")
            .AppendLine("    private readonly System.Collections.Generic.Dictionary<string, TwinCatRxHashTable> " +
                "_twinCatRxStructures = new(StringComparer.OrdinalIgnoreCase);")
            .AppendLine();

        AppendConnectionFields(sb, spec.Properties);
        AppendConnectionProperties(sb, spec.Properties);
        AppendSettingsFactory(sb, spec);
        AppendConnectMethod(sb);
        AppendBindingMethod(sb, spec.Properties);
        AppendNotificationMethods(sb, spec.Properties);
        AppendWriteMethods(sb, spec.Properties);

        _ = sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Appends generated signal fields.</summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="properties">The PLC property specifications.</param>
    private static void AppendConnectionFields(StringBuilder sb, IReadOnlyList<PlcPropertySpec> properties)
    {
        foreach (var property in properties)
        {
            _ = sb.Append("    private readonly global::ReactiveUI.Primitives.Signals.BehaviorSignal<")
                .Append(property.TypeName).Append("> ").Append(property.SubjectField).AppendLine(" = new(default!);");
        }

        if (!HasNotificationProperties(properties))
        {
            return;
        }

        _ = sb.AppendLine();
    }

    /// <summary>Appends generated client and observable properties.</summary>
    /// <param name="sb">The string builder.</param>
    /// <param name="properties">The PLC property specifications.</param>
    private static void AppendConnectionProperties(StringBuilder sb, IReadOnlyList<PlcPropertySpec> properties)
    {
        _ = sb.AppendLine("    public TwinCatRxClientContract? TwinCatRxClient => _twinCatRxClient;")
            .AppendLine("    public TwinCatRxLogicalTags? TwinCatRxLogicalTags => _twinCatRxLogicalTags;")
            .AppendLine();

        var structuredVariables = GetStructuredVariables(properties);
        foreach (var property in properties)
        {
            _ = sb.Append("    public IObservable<").Append(property.TypeName).Append("> ")
                .Append(property.ObservableName).Append(" => ").Append(property.SubjectField).AppendLine(";")
                .Append("    public global::ReactiveUI.Primitives.Async.IObservableAsync<")
                .Append(property.TypeName).Append("> ").Append(property.ObservableName)
                .Append("Async => TwinCatRxObservableBridge.ToAsyncObservable(")
                .Append(property.ObservableName).AppendLine(");");

            AppendLogicalTagDeclaration(sb, property, structuredVariables);
            if (property.Kind != WriteOnlyKind)
            {
                _ = sb.Append(AsyncResultMethodPrefix).Append(property.TypeName).Append(">> ")
                    .Append(property.ReadMethodName)
                    .AppendLine("Async(System.Threading.CancellationToken cancellationToken = default) =>")
                    .Append("        ");
                _ = AppendTypedLogicalTagOperation(sb, "ReadAsync", property.TypeName, property.PropertyName)
                    .AppendLine(", cancellationToken);");
            }

            if (property.IsWritable)
            {
                _ = sb.Append("    public async System.Threading.Tasks.Task<")
                    .Append("global::IoT.DriverCore.Core.TagOperationResult<").Append(property.TypeName).Append(">> ")
                    .Append(property.WriteMethodName).Append("Async(").Append(property.TypeName)
                    .AppendLine(" value, System.Threading.CancellationToken cancellationToken = default)")
                    .AppendLine(ClassOpenBrace)
                    .Append("        var result = await ");
                _ = AppendTypedLogicalTagOperation(sb, "WriteAsync", property.TypeName, property.PropertyName)
                    .AppendLine(", value, cancellationToken).ConfigureAwait(false);");
                if (property.Kind == WriteOnlyKind)
                {
                    _ = sb.AppendLine("        if (result.Succeeded)")
                        .AppendLine(BlockOpenBrace)
                        .Append("            ").Append(property.SetterName).AppendLine("(value);")
                        .AppendLine(BlockCloseBrace);
                }

                _ = sb.AppendLine("        return result;")
                    .AppendLine(ClassCloseBrace);
            }

            _ = sb
                .AppendLine();
        }
    }

    /// <summary>Appends one public CP.IoT logical tag declaration.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="property">The PLC property.</param>
    /// <param name="structuredVariables">The known structure roots.</param>
    private static void AppendLogicalTagDeclaration(
        StringBuilder sb,
        PlcPropertySpec property,
        IReadOnlyList<string> structuredVariables)
    {
        var structuredTarget = GetStructuredWriteTarget(property, structuredVariables);
        var logicalAddress = structuredTarget is null
            ? property.Address
            : CombineAddress(structuredTarget.RootAddress, structuredTarget.MemberAddress);
        var accessMode = "Read";
        if (property.Kind == WriteOnlyKind)
        {
            accessMode = "Write";
        }
        else if (property.IsWritable)
        {
            accessMode = "ReadWrite";
        }

        _ = sb.Append("    public global::IoT.DriverCore.Core.LogicalTag ").Append(property.PropertyName)
            .Append("Tag => new global::IoT.DriverCore.Core.LogicalTag(nameof(").Append(property.PropertyName)
            .Append("), \"").Append(Escape(logicalAddress)).Append("\", typeof(").Append(property.TypeName)
            .Append(").FullName ?? typeof(").Append(property.TypeName)
            .Append(").Name, new global::IoT.DriverCore.Core.LogicalTagOptions")
            .AppendLine()
            .AppendLine("        {");

        var writeAddress = GetWriteAddress(property);
        if (structuredTarget is not null ||
            !string.Equals(writeAddress, property.Address, StringComparison.OrdinalIgnoreCase))
        {
            _ = sb.AppendLine("            Metadata = new System.Collections.Generic.Dictionary<string, string>(" +
                    "StringComparer.Ordinal)")
                .AppendLine("            {");
            if (structuredTarget is not null)
            {
                _ = sb.Append("            [\"StructureRoot\"] = \"")
                    .Append(Escape(structuredTarget.RootAddress)).AppendLine("\",")
                    .Append("            [\"MemberAddress\"] = \"")
                    .Append(Escape(structuredTarget.MemberAddress)).AppendLine("\",");
            }
            else
            {
                _ = sb.Append("            [\"WriteAddress\"] = \"").Append(Escape(writeAddress)).AppendLine("\",");
            }

            _ = sb.AppendLine("            },");
        }

        _ = sb.Append("            AccessMode = global::IoT.DriverCore.Core.LogicalTagAccessMode.")
            .Append(accessMode).AppendLine(",")
            .AppendLine("        });");
    }

    /// <summary>Appends a typed logical-tag mixin call through the generated client.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="operation">The logical-tag mixin operation name.</param>
    /// <param name="typeName">The generated property type.</param>
    /// <param name="propertyName">The generated property name.</param>
    /// <returns>The supplied <paramref name="sb"/> for continued emission.</returns>
    private static StringBuilder AppendTypedLogicalTagOperation(
        StringBuilder sb,
        string operation,
        string typeName,
        string propertyName) =>
        sb.Append("global::IoT.DriverCore.Core.LogicalTagMixins.")
            .Append(operation)
            .Append('<')
            .Append(typeName)
            .Append(">(RequireTwinCatRxLogicalTags(), new global::IoT.DriverCore.Core.LogicalTagKey<")
            .Append(typeName)
            .Append(">(nameof(")
            .Append(propertyName)
            .Append("))");

    /// <summary>Appends live logical-tag registry initialization for generated properties.</summary>
    /// <param name="sb">The generated source builder.</param>
    /// <param name="properties">The PLC properties.</param>
    private static void AppendLogicalTagRegistrations(StringBuilder sb, IReadOnlyList<PlcPropertySpec> properties)
    {
        foreach (var property in properties)
        {
            _ = sb.Append("        logicalTags.RegisterTag(").Append(property.PropertyName).AppendLine("Tag);");
        }
    }
}
