// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Text;

namespace IoT.Driver.MitsubishiRx;

/// <summary>Emits strongly typed Mitsubishi tag client source.</summary>
internal static partial class MitsubishiTagClientEmitter
{
    /// <summary>Indentation used for generated type members.</summary>
    private const int MemberIndentation = 4;

    /// <summary>Generated line containing a close brace indented by four spaces.</summary>
    private const string IndentedCloseBrace = "    }";

    /// <summary>Generated line containing an open brace indented by four spaces.</summary>
    private const string IndentedOpenBrace = "    {";

    /// <summary>Generated line containing a close brace indented by eight spaces.</summary>
    private const string NestedCloseBrace = "        }";

    /// <summary>Generated line containing an open brace indented by eight spaces.</summary>
    private const string NestedOpenBrace = "        {";

    /// <summary>Generated line returning the default value indented by twelve spaces.</summary>
    private const string ReturnDefault = "            return default;";

    /// <summary>Converts a schema name into a valid C# identifier.</summary>
    /// <param name="value">Schema name.</param>
    /// <returns>A valid C# identifier.</returns>
    internal static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "Tag";
        }

        var builder = new StringBuilder();
        bool capitalize = true;
        foreach (char ch in value)
        {
            if (char.IsLetterOrDigit(ch))
            {
                _ = builder.Append(capitalize ? char.ToUpperInvariant(ch) : ch);
                capitalize = false;
            }
            else
            {
                capitalize = true;
            }
        }

        if (builder.Length == 0)
        {
            _ = builder.Append("Tag");
        }

        if (!char.IsLetter(builder[0]) && builder[0] != '_')
        {
            _ = builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    /// <summary>Emits helpers for property-level logical-tag bindings.</summary>
    /// <param name="bindings">The property bindings.</param>
    /// <returns>The generated source.</returns>
    internal static string EmitPropertyBindings(
        IReadOnlyList<MitsubishiTagClientGenerator.PropertyBindingModel> bindings)
    {
        var builder = new StringBuilder();
        AppendLine(builder, "// <auto-generated />");
        var groups = new Dictionary<(string NamespaceName, string TypeName), List<MitsubishiTagClientGenerator.PropertyBindingModel>>();
        var orderedGroupKeys = new List<(string NamespaceName, string TypeName)>();
        foreach (var binding in bindings)
        {
            var key = (binding.NamespaceName, binding.TypeName);
            if (!groups.TryGetValue(key, out var group))
            {
                group = [];
                groups.Add(key, group);
                orderedGroupKeys.Add(key);
            }

            group.Add(binding);
        }

        foreach (var key in orderedGroupKeys)
        {
            var group = groups[key];
            if (!string.IsNullOrWhiteSpace(key.NamespaceName))
            {
                AppendLine(builder, $"namespace {key.NamespaceName}");
                AppendLine(builder, "{");
            }

            AppendLine(builder, $"partial class {key.TypeName}");
            AppendLine(builder, "{");
            foreach (var binding in group)
            {
                var escapedTagName = binding.TagName.Replace("\\", "\\\\").Replace("\"", "\\\"");
                AppendPropertyBinding(builder, binding, escapedTagName);
            }

            AppendLine(builder, "}");
            if (!string.IsNullOrWhiteSpace(key.NamespaceName))
            {
                AppendLine(builder, "}");
            }
        }

        return builder.ToString();
    }

    /// <summary>Appends the generated members for a property-level logical tag binding.</summary>
    /// <param name="builder">The target generated-source builder.</param>
    /// <param name="binding">The binding to emit.</param>
    /// <param name="escapedTagName">The escaped logical tag name.</param>
    internal static void AppendPropertyBinding(
        StringBuilder builder,
        MitsubishiTagClientGenerator.PropertyBindingModel binding,
        string escapedTagName)
    {
        AppendMemberDocumentation(builder, $"Observes updates for the {binding.TagName} logical tag.");
        AppendLine(
            builder,
            $"    public global::System.IObservable<{binding.PropertyType}> " +
            $"{binding.PropertyName}Observable => {binding.ClientMemberName}" +
            $".Observe(new global::IoT.Driver.Core.LogicalTagKey<{binding.PropertyType}>(" +
            $"\"{escapedTagName}\"));");
        AppendMemberDocumentation(builder, $"Asynchronously observes updates for the {binding.TagName} logical tag.");
        AppendLine(
            builder,
            string.Concat(
                $"    public global::System.Collections.Generic.IAsyncEnumerable<{binding.PropertyType}> ",
                $"{binding.PropertyName}ObservableAsync => {binding.ClientMemberName}",
                $".ObserveAsync(new global::IoT.Driver.Core.LogicalTagKey<{binding.PropertyType}>(",
                $"\"{escapedTagName}\"), ",
                "global::System.Threading.CancellationToken.None);"));
        AppendMemberDocumentation(builder, $"Reads the {binding.TagName} logical tag.");
        AppendLine(
            builder,
            string.Concat(
                "    public global::System.Threading.Tasks.Task<global::IoT.Driver.Core.",
                $"TagOperationResult<{binding.PropertyType}>> Read{binding.PropertyName}Async(",
                "global::System.Threading.CancellationToken cancellationToken = default) => ",
                $"{binding.ClientMemberName}.ReadAsync(",
                $"new global::IoT.Driver.Core.LogicalTagKey<{binding.PropertyType}>(",
                $"\"{escapedTagName}\"), ",
                "cancellationToken);"));
        AppendMemberDocumentation(builder, $"Writes the {binding.TagName} logical tag.");
        AppendLine(
            builder,
            string.Concat(
                "    public global::System.Threading.Tasks.Task<global::IoT.Driver.Core.",
                $"TagOperationResult<{binding.PropertyType}>> Write{binding.PropertyName}Async(",
                $"{binding.PropertyType} value, ",
                "global::System.Threading.CancellationToken cancellationToken = default) => ",
                $"{binding.ClientMemberName}.WriteAsync(\"{escapedTagName}\", value, cancellationToken);"));
    }

    /// <summary>Emits generated client source for the supplied schema model.</summary>
    /// <param name="model">Parsed schema model.</param>
    /// <returns>Generated client source.</returns>
    internal static string Emit(MitsubishiTagClientGenerator.SchemaModel model)
    {
        var builder = new StringBuilder();
        AppendLine(builder, "// <auto-generated />");
        AppendLine(builder, "using System;");
        AppendLine(builder, "using System.Collections.Generic;");
        AppendLine(builder, "using System.Linq;");
        AppendLine(builder, "using System.Threading;");
        AppendLine(builder, "using System.Threading.Tasks;");
        AppendLine(builder, "using IoT.Driver.Core;");
        AppendLine(builder, "using ReactiveUI.Primitives;");
        AppendLine(builder);
        AppendLine(builder, $"namespace {model.NamespaceName};");
        AppendLine(builder);
        AppendGeneratedClientExtensions(builder, model.NamespaceName);
        AppendGeneratedClient(builder, model.NamespaceName);
        AppendTagClient(builder, model.Tags, model.NamespaceName);
        AppendGroupClient(builder, model.Groups, model.NamespaceName);

        foreach (var tag in model.Tags)
        {
            AppendTagType(builder, tag.Name, tag.DataType, model.NamespaceName);
        }

        foreach (var group in model.Groups)
        {
            AppendGroupSnapshotType(builder, group, model.Tags);
            AppendGroupType(builder, group, model.NamespaceName);
        }

        return builder.ToString();
    }

    /// <summary>Gets the generated field declaration for a runtime-specific Mitsubishi client.</summary>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    /// <returns>The generated field declaration.</returns>
    private static string GetOwnerField(string namespaceName)
        => $"    private readonly global::{namespaceName}.MitsubishiRx _owner;";

    /// <summary>Appends the generated client extension class.</summary>
    /// <param name="builder">The target generated-source builder.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendGeneratedClientExtensions(StringBuilder builder, string namespaceName)
    {
        AppendDocumentation(builder, "Provides access to generated Mitsubishi tag clients.");
        AppendLine(builder, "public static class GeneratedMitsubishiTagClientExtensions");
        AppendLine(builder, "{");
        AppendMemberDocumentation(builder, "Creates a generated tag client for the Mitsubishi PLC client.");
        AppendLine(
            builder,
            $"    public static GeneratedMitsubishiTagClient Generated(this global::{namespaceName}.MitsubishiRx owner) => new(owner);");
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends the generated client class.</summary>
    /// <param name="builder">The target generated-source builder.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendGeneratedClient(StringBuilder builder, string namespaceName)
    {
        AppendDocumentation(builder, "Provides generated tag and group accessors.");
        AppendLine(builder, "public sealed partial class GeneratedMitsubishiTagClient");
        AppendLine(builder, "{");
        AppendLine(builder, GetOwnerField(namespaceName));
        AppendLine(builder);
        AppendMemberDocumentation(builder, "Initializes a generated tag client.");
        AppendLine(builder, $"    public GeneratedMitsubishiTagClient(global::{namespaceName}.MitsubishiRx owner)");
        AppendLine(builder, IndentedOpenBrace);
        AppendLine(builder, "        _owner = owner ?? throw new ArgumentNullException(nameof(owner));");
        AppendLine(builder, "        Tags = new TagsClient(owner);");
        AppendLine(builder, "        Groups = new GroupsClient(owner);");
        AppendLine(builder, IndentedCloseBrace);
        AppendLine(builder);
        AppendMemberDocumentation(builder, "Gets the generated tag accessors.");
        AppendLine(builder, "    public TagsClient Tags { get; }");
        AppendLine(builder);
        AppendMemberDocumentation(builder, "Gets the generated group accessors.");
        AppendLine(builder, "    public GroupsClient Groups { get; }");
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends the generated tag-accessor class.</summary>
    /// <param name="builder">The target generated-source builder.</param>
    /// <param name="tags">The schema tags.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendTagClient(
        StringBuilder builder,
        IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags,
        string namespaceName)
    {
        AppendDocumentation(builder, "Provides generated accessors for schema tags.");
        AppendLine(builder, "public sealed class TagsClient");
        AppendLine(builder, "{");
        AppendLine(builder, GetOwnerField(namespaceName));
        AppendMemberDocumentation(builder, "Initializes the generated tag accessor collection.");
        AppendLine(builder, $"    public TagsClient(global::{namespaceName}.MitsubishiRx owner) => _owner = owner;");

        foreach (var tag in tags)
        {
            string propertyName = SanitizeIdentifier(tag.Name);
            string nestedType = $"{propertyName}Tag";
            AppendMemberDocumentation(builder, $"Gets the generated accessor for the {tag.Name} tag.");
            AppendLine(builder, $"    public {nestedType} {propertyName} => new(_owner);");
        }

        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends the generated group-accessor class.</summary>
    /// <param name="builder">The target generated-source builder.</param>
    /// <param name="groups">The schema groups.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendGroupClient(
        StringBuilder builder,
        IReadOnlyList<MitsubishiTagClientGenerator.GroupModel> groups,
        string namespaceName)
    {
        AppendDocumentation(builder, "Provides generated accessors for schema groups.");
        AppendLine(builder, "public sealed class GroupsClient");
        AppendLine(builder, "{");
        AppendLine(builder, GetOwnerField(namespaceName));
        AppendMemberDocumentation(builder, "Initializes the generated group accessor collection.");
        AppendLine(builder, $"    public GroupsClient(global::{namespaceName}.MitsubishiRx owner) => _owner = owner;");
        foreach (var group in groups)
        {
            string propertyName = SanitizeIdentifier(group.Name);
            string nestedType = $"{propertyName}Group";
            AppendMemberDocumentation(builder, $"Gets the generated accessor for the {group.Name} group.");
            AppendLine(builder, $"    public {nestedType} {propertyName} => new(_owner);");
        }

        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends a generated tag client type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="tagName">Schema tag name.</param>
    /// <param name="dataType">Schema data type.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendTagType(StringBuilder builder, string tagName, string? dataType, string namespaceName)
    {
        string propertyName = SanitizeIdentifier(tagName);
        string nestedType = $"{propertyName}Tag";
        string escapedTagName = tagName.Replace("\"", "\\\"");
        string readType = ResolveReadType(dataType);
        string readMethod = ResolveReadMethod(dataType);
        string writeType = ResolveWriteType(dataType);
        string writeMethod = ResolveWriteMethod(dataType);

        AppendDocumentation(builder, $"Provides operations for the {tagName} tag.");
        AppendLine(builder, $"public sealed class {nestedType}");
        AppendLine(builder, "{");
        AppendLine(builder, GetOwnerField(namespaceName));
        AppendMemberDocumentation(builder, $"Initializes the {tagName} tag accessor.");
        AppendLine(builder, $"    public {nestedType}(global::{namespaceName}.MitsubishiRx owner) => _owner = owner;");
        AppendMemberDocumentation(builder, $"Reads the {tagName} tag.");
        AppendLine(
            builder,
            string.Concat(
                $"    public Task<Responce<{readType}>> ReadAsync(",
                "CancellationToken cancellationToken = default) => ",
                $"_owner.{readMethod}(\"{escapedTagName}\", cancellationToken);"));
        AppendMemberDocumentation(builder, $"Writes the {tagName} tag.");
        AppendLine(
            builder,
            string.Concat(
                $"    public Task<Responce> WriteAsync({writeType} value, ",
                "CancellationToken cancellationToken = default) => ",
                $"_owner.{writeMethod}(\"{escapedTagName}\", value, cancellationToken);"));
        AppendMemberDocumentation(builder, $"Observes updates for the {tagName} tag.");
        AppendLine(
            builder,
            string.Concat(
                $"    public IObservable<MitsubishiReactiveValue<{readType}>> Observe(",
                "TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null) => ",
                $"_owner.ObserveReactiveTag(new LogicalTagKey<{readType}>(\"{escapedTagName}\"), ",
                "pollInterval, minimumUpdateSpacing);"));
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends a generated group client type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="group">Schema group.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendGroupType(
        StringBuilder builder,
        MitsubishiTagClientGenerator.GroupModel group,
        string namespaceName)
    {
        string groupName = group.Name;
        string propertyName = SanitizeIdentifier(groupName);
        string nestedType = $"{propertyName}Group";
        string snapshotType = $"{propertyName}Snapshot";
        string escapedGroupName = groupName.Replace("\"", "\\\"");
        AppendGroupHeader(builder, groupName, nestedType, namespaceName);
        AppendGroupReadMembers(builder, groupName, snapshotType, escapedGroupName);
        AppendGroupWriteAndObserveMembers(builder, groupName, snapshotType, escapedGroupName);
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Appends a generated group type header.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="groupName">Schema group name.</param>
    /// <param name="nestedType">Generated group type name.</param>
    /// <param name="namespaceName">The namespace that owns the Mitsubishi runtime.</param>
    private static void AppendGroupHeader(
        StringBuilder builder,
        string groupName,
        string nestedType,
        string namespaceName)
    {
        AppendDocumentation(builder, $"Provides operations for the {groupName} tag group.");
        AppendLine(builder, $"public sealed class {nestedType}");
        AppendLine(builder, "{");
        AppendLine(builder, GetOwnerField(namespaceName));
        AppendMemberDocumentation(builder, $"Initializes the {groupName} group accessor.");
        AppendLine(builder, $"    public {nestedType}(global::{namespaceName}.MitsubishiRx owner) => _owner = owner;");
    }

    /// <summary>Appends the generated group read members.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="groupName">Schema group name.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="escapedGroupName">Escaped schema group name.</param>
    private static void AppendGroupReadMembers(
        StringBuilder builder,
        string groupName,
        string snapshotType,
        string escapedGroupName)
    {
        AppendGroupReadMember(builder, groupName, snapshotType, escapedGroupName, false);
        AppendLine(builder);
        AppendGroupReadMember(builder, groupName, snapshotType, escapedGroupName, true);
        AppendLine(builder);
    }

    /// <summary>Appends one generated group read member.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="groupName">Schema group name.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="escapedGroupName">Escaped schema group name.</param>
    /// <param name="optional">Whether the generated result is optional.</param>
    private static void AppendGroupReadMember(
        StringBuilder builder,
        string groupName,
        string snapshotType,
        string escapedGroupName,
        bool optional)
    {
        string nullableMarker = optional ? "?" : string.Empty;
        string methodName = optional ? "ReadOptionalAsync" : "ReadAsync";
        string mapperName = optional ? "TryFromSnapshot" : "FromSnapshot";
        string description = optional ? " when available" : string.Empty;
        AppendMemberDocumentation(builder, $"Reads the {groupName} group snapshot{description}.");
        AppendLine(builder, $"    public async Task<Responce<{snapshotType}{nullableMarker}>> {methodName}(");
        AppendLine(builder, "        CancellationToken cancellationToken = default)");
        AppendLine(builder, IndentedOpenBrace);
        AppendLine(builder, $"        var result = await _owner.ReadTagGroupSnapshotAsync(\"{escapedGroupName}\", ");
        AppendLine(builder, "            cancellationToken).ConfigureAwait(false);");
        AppendLine(builder, "        if (!result.IsSucceed || result.Value is null)");
        AppendLine(builder, NestedOpenBrace);
        AppendLine(builder, $"            return new Responce<{snapshotType}{nullableMarker}>(result);");
        AppendLine(builder, NestedCloseBrace);
        AppendLine(builder);
        AppendLine(builder, $"        return new Responce<{snapshotType}{nullableMarker}>(result, ");
        AppendLine(builder, $"            {snapshotType}.{mapperName}(result.Value));");
        AppendLine(builder, IndentedCloseBrace);
    }

    /// <summary>Appends the generated group write and observation members.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="groupName">Schema group name.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="escapedGroupName">Escaped schema group name.</param>
    private static void AppendGroupWriteAndObserveMembers(
        StringBuilder builder,
        string groupName,
        string snapshotType,
        string escapedGroupName)
    {
        AppendMemberDocumentation(builder, $"Writes the {groupName} group snapshot.");
        AppendLine(builder, $"    public Task<Responce> WriteAsync({snapshotType} value, ");
        AppendLine(builder, "        CancellationToken cancellationToken = default) =>");
        AppendLine(builder, "        _owner.WriteTagGroupSnapshotAsync(value.ToSnapshot(), cancellationToken);");
        AppendLine(builder);
        AppendGroupObserveMember(builder, groupName, snapshotType, escapedGroupName, false);
        AppendLine(builder);
        AppendGroupObserveMember(builder, groupName, snapshotType, escapedGroupName, true);
    }

    /// <summary>Appends one generated group observation member.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="groupName">Schema group name.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="escapedGroupName">Escaped schema group name.</param>
    /// <param name="optional">Whether the generated result is optional.</param>
    private static void AppendGroupObserveMember(
        StringBuilder builder,
        string groupName,
        string snapshotType,
        string escapedGroupName,
        bool optional)
    {
        string nullableMarker = optional ? "?" : string.Empty;
        string methodName = optional ? "ObserveOptional" : "Observe";
        string mapperName = optional ? "MapReactiveOptional" : "MapReactive";
        string description = optional ? "optional " : string.Empty;
        AppendMemberDocumentation(builder, $"Observes {description}updates for the {groupName} group.");
        AppendLine(
            builder,
            $"    public IObservable<MitsubishiReactiveValue<{snapshotType}{nullableMarker}>> " +
            $"{methodName}(");
        AppendLine(builder, "        TimeSpan pollInterval, TimeSpan? minimumUpdateSpacing = null)");
        AppendLine(builder, $"        => _owner.ObserveReactiveTagGroup(\"{escapedGroupName}\", ");
        AppendLine(builder, "            pollInterval, minimumUpdateSpacing)");
        AppendLine(builder, $"            .Select(static value => {snapshotType}.{mapperName}(value));");
    }

    /// <summary>Appends a generated group snapshot type.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="group">Schema group.</param>
    /// <param name="tags">All schema tags.</param>
    private static void AppendGroupSnapshotType(
        StringBuilder builder,
        MitsubishiTagClientGenerator.GroupModel group,
        IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        string snapshotType = $"{SanitizeIdentifier(group.Name)}Snapshot";
        string escapedGroupName = group.Name.Replace("\"", "\\\"");
        var orderedTags = GetOrderedGroupTags(group, tags);
        AppendSnapshotHeader(builder, snapshotType, orderedTags);
        AppendSnapshotFactoryMember(builder, snapshotType, orderedTags, false);
        AppendLine(builder);
        AppendSnapshotFactoryMember(builder, snapshotType, orderedTags, true);
        AppendLine(builder);
        AppendSnapshotWriteMember(builder, escapedGroupName, orderedTags);
        AppendLine(builder);
        AppendReactiveMappingMembers(builder, snapshotType);
        AppendLine(builder, "}");
        AppendLine(builder);
    }

    /// <summary>Gets the tags included in a generated group snapshot.</summary>
    /// <param name="group">Schema group.</param>
    /// <param name="tags">All schema tags.</param>
    /// <returns>The group tags in schema order.</returns>
    private static List<MitsubishiTagClientGenerator.TagModel> GetOrderedGroupTags(
        MitsubishiTagClientGenerator.GroupModel group,
        IReadOnlyList<MitsubishiTagClientGenerator.TagModel> tags)
    {
        var orderedTags = new List<MitsubishiTagClientGenerator.TagModel>(group.TagNames.Count);
        foreach (var name in group.TagNames)
        {
            foreach (var tag in tags)
            {
                if (string.Equals(tag.Name, name, StringComparison.Ordinal))
                {
                    orderedTags.Add(tag);
                    break;
                }
            }
        }

        return orderedTags;
    }

    /// <summary>Appends a generated group snapshot declaration.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    private static void AppendSnapshotHeader(
        StringBuilder builder,
        string snapshotType,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags)
    {
        var parametersBuilder = new StringBuilder();
        for (int i = 0; i < orderedTags.Count; i++)
        {
            if (i > 0)
            {
                _ = parametersBuilder.Append(", ");
            }

            var tag = orderedTags[i];
            _ = parametersBuilder.Append(ResolveReadType(tag.DataType));
            _ = parametersBuilder.Append(' ');
            _ = parametersBuilder.Append(SanitizeIdentifier(tag.Name));
        }

        string parameters = parametersBuilder.ToString();
        AppendDocumentation(builder, "Represents a generated tag group snapshot.");
        AppendLine(builder, $"public sealed partial record {snapshotType}({parameters})");
        AppendLine(builder, "{");
    }

    /// <summary>Appends a generated snapshot factory member.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    /// <param name="optional">Whether the factory permits missing values.</param>
    private static void AppendSnapshotFactoryMember(
        StringBuilder builder,
        string snapshotType,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags,
        bool optional)
    {
        string nullableMarker = optional ? "?" : string.Empty;
        string methodName = optional ? "TryFromSnapshot" : "FromSnapshot";
        AppendMemberDocumentation(builder, "Creates a typed snapshot from an untyped tag group snapshot.");
        AppendLine(builder, $"    public static {snapshotType}{nullableMarker} {methodName}(");
        AppendLine(builder, $"        MitsubishiTagGroupSnapshot{nullableMarker} snapshot)");
        if (optional)
        {
            AppendOptionalSnapshotFactoryBody(builder, snapshotType, orderedTags);
            return;
        }

        AppendLine(builder, IndentedOpenBrace);
        AppendLine(builder, "        ArgumentNullException.ThrowIfNull(snapshot);");
        AppendSnapshotConstruction(builder, snapshotType, orderedTags, "        ");
        AppendLine(builder, IndentedCloseBrace);
    }

    /// <summary>Appends an optional generated snapshot factory body.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    private static void AppendOptionalSnapshotFactoryBody(
        StringBuilder builder,
        string snapshotType,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags)
    {
        AppendLine(builder, IndentedOpenBrace);
        AppendLine(builder, "        if (snapshot is null)");
        AppendLine(builder, NestedOpenBrace);
        AppendLine(builder, ReturnDefault);
        AppendLine(builder, NestedCloseBrace);
        AppendLine(builder, "        try");
        AppendLine(builder, NestedOpenBrace);
        AppendSnapshotConstruction(builder, snapshotType, orderedTags, "            ");
        AppendLine(builder, NestedCloseBrace);
        AppendLine(builder, "        catch (KeyNotFoundException)");
        AppendLine(builder, NestedOpenBrace);
        AppendLine(builder, ReturnDefault);
        AppendLine(builder, NestedCloseBrace);
        AppendLine(builder, "        catch (InvalidCastException)");
        AppendLine(builder, NestedOpenBrace);
        AppendLine(builder, ReturnDefault);
        AppendLine(builder, NestedCloseBrace);
        AppendLine(builder, "    }");
    }

    /// <summary>Appends a generated snapshot constructor invocation.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="snapshotType">Generated snapshot type name.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    /// <param name="indentation">Generated source indentation.</param>
    private static void AppendSnapshotConstruction(
        StringBuilder builder,
        string snapshotType,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags,
        string indentation)
    {
        AppendLine(builder, $"{indentation}return new {snapshotType}(");
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            string escapedTagName = tag.Name.Replace("\"", "\\\"");
            AppendLine(builder, $"{indentation}    snapshot.GetRequired(");
            AppendLine(
                builder,
                $"        new LogicalTagKey<{ResolveReadType(tag.DataType)}>(\"{escapedTagName}\")){suffix}");
        }

        AppendLine(builder, $"{indentation});");
    }

    /// <summary>Appends a generated group snapshot write member.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="escapedGroupName">Escaped schema group name.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    private static void AppendSnapshotWriteMember(
        StringBuilder builder,
        string escapedGroupName,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags)
    {
        AppendMemberDocumentation(builder, "Creates an untyped tag group snapshot.");
        AppendLine(builder, "    public MitsubishiTagGroupSnapshot ToSnapshot()");
        AppendLine(builder, "    {");
        AppendLine(builder, "        return new MitsubishiTagGroupSnapshot(");
        AppendLine(builder, $"            \"{escapedGroupName}\",");
        AppendLine(builder, "            new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)");
        AppendLine(builder, "            {");
        AppendSnapshotValues(builder, orderedTags);
        AppendLine(builder, "            });");
        AppendLine(builder, "    }");
    }

    /// <summary>Appends the values of a generated group snapshot.</summary>
    /// <param name="builder">Source builder.</param>
    /// <param name="orderedTags">Tags in the generated group.</param>
    private static void AppendSnapshotValues(
        StringBuilder builder,
        List<MitsubishiTagClientGenerator.TagModel> orderedTags)
    {
        for (int i = 0; i < orderedTags.Count; i++)
        {
            var tag = orderedTags[i];
            string suffix = i == orderedTags.Count - 1 ? string.Empty : ",";
            string escapedTagName = tag.Name.Replace("\"", "\\\"");
            AppendLine(builder, $"                [\"{escapedTagName}\"] = ");
            AppendLine(builder, $"                    {SanitizeIdentifier(tag.Name)}{suffix}");
        }
    }
}
