// Copyright (c) 2019-2026 Chris Pulman and contributors. All rights reserved.
// Chris Pulman and contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MitsubishiRx;

/// <summary>Generates strongly typed Mitsubishi tag clients from embedded tag schema JSON.</summary>
[Generator]
public sealed partial class MitsubishiTagClientGenerator : IIncrementalGenerator
{
    /// <summary>Attribute source added to consuming compilations.</summary>
    private const string AttributeSource = """
// <auto-generated />
using System;

namespace MitsubishiRx;

/// <summary>Declares an inline Mitsubishi tag schema.</summary>
[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public sealed class MitsubishiTagClientSchemaAttribute : Attribute
{
    /// <summary>Initializes a schema attribute.</summary>
    /// <param name="schemaJson">The JSON tag schema.</param>
    public MitsubishiTagClientSchemaAttribute(string schemaJson)
    {
        SchemaJson = schemaJson ?? throw new ArgumentNullException(nameof(schemaJson));
    }

    /// <summary>Gets the JSON tag schema.</summary>
    public string SchemaJson { get; }
}

/// <summary>Binds generated tag members to a Mitsubishi client member.</summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class MitsubishiTagClientAttribute : Attribute
{
    /// <summary>Initializes a client binding attribute.</summary>
    /// <param name="clientMemberName">The client field or property name.</param>
    public MitsubishiTagClientAttribute(string clientMemberName = "LogicalTags")
    {
        ClientMemberName = clientMemberName ?? throw new ArgumentNullException(nameof(clientMemberName));
    }

    /// <summary>Gets the client field or property name.</summary>
    public string ClientMemberName { get; }
}

/// <summary>Binds a generated property to a logical Mitsubishi tag name.</summary>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
public sealed class MitsubishiTagAttribute : Attribute
{
    /// <summary>Initializes a tag binding attribute.</summary>
    /// <param name="tagName">The logical tag name.</param>
    public MitsubishiTagAttribute(string tagName)
    {
        TagName = tagName ?? throw new ArgumentNullException(nameof(tagName));
    }

    /// <summary>Gets the logical tag name.</summary>
    public string TagName { get; }
}
""";

    /// <summary>Diagnostic reported when generation fails unexpectedly.</summary>
    private static readonly DiagnosticDescriptor GenerationFailureDiagnostic = new(
        id: "MRTXGEN001",
        title: "Failed to generate Mitsubishi tag client",
        messageFormat: "{0}",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when tag names are duplicated.</summary>
    private static readonly DiagnosticDescriptor DuplicateTagDiagnostic = new(
        id: "MRTXGEN002",
        title: "Duplicate generated tag name",
        messageFormat: "Schema contains duplicate tag name '{0}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group references a missing tag.</summary>
    private static readonly DiagnosticDescriptor UnknownGroupTagDiagnostic = new(
        id: "MRTXGEN003",
        title: "Unknown generated group tag reference",
        messageFormat: "Group '{0}' references unknown tag '{1}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a tag has an unsupported data type.</summary>
    private static readonly DiagnosticDescriptor UnsupportedDataTypeDiagnostic = new(
        id: "MRTXGEN004",
        title: "Unsupported generated tag data type",
        messageFormat: "Tag '{0}' uses unsupported data type '{1}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when different schema names sanitize to the same identifier.</summary>
    private static readonly DiagnosticDescriptor SanitizedIdentifierCollisionDiagnostic = new(
        id: "MRTXGEN005",
        title: "Generated identifier collision",
        messageFormat: "Generated identifier '{0}' is produced by multiple {1}: {2}",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a tag has no name.</summary>
    private static readonly DiagnosticDescriptor EmptyTagNameDiagnostic = new(
        id: "MRTXGEN006",
        title: "Empty generated tag name",
        messageFormat: "Tag name must not be empty",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group has no name.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupNameDiagnostic = new(
        id: "MRTXGEN007",
        title: "Empty generated group name",
        messageFormat: "Group name must not be empty",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group has no tag members.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupMembershipDiagnostic = new(
        id: "MRTXGEN008",
        title: "Empty generated group membership",
        messageFormat: "Group '{0}' must reference at least one tag",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when group names are duplicated.</summary>
    private static readonly DiagnosticDescriptor DuplicateGroupDiagnostic = new(
        id: "MRTXGEN009",
        title: "Duplicate generated group name",
        messageFormat: "Schema contains duplicate group name '{0}'",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group contains an empty tag reference.</summary>
    private static readonly DiagnosticDescriptor EmptyGroupTagReferenceDiagnostic = new(
        id: "MRTXGEN010",
        title: "Empty generated group tag reference",
        messageFormat: "Group '{0}' contains an empty tag reference",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Diagnostic reported when a group references the same tag more than once.</summary>
    private static readonly DiagnosticDescriptor DuplicateGroupTagReferenceDiagnostic = new(
        id: "MRTXGEN011",
        title: "Duplicate generated group tag reference",
        messageFormat: "Group '{0}' references tag '{1}' more than once",
        category: "MitsubishiRx.Generators",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <summary>Supported schema data types.</summary>
    private static readonly HashSet<string> SupportedDataTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "Bit",
        "Word",
        "DWord",
        "Float",
        "String",
        "Int16",
        "UInt16",
        "Int32",
        "UInt32",
    };

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static productionContext =>
            productionContext.AddSource(
                "MitsubishiTagClientSchemaAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        var schemaValues = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is AttributeSyntax attribute && MightBeSchemaAttribute(attribute),
                transform: static (syntaxContext, _) => ExtractSchemaLiteral(syntaxContext))
            .Where(static schema => !string.IsNullOrWhiteSpace(schema))
            .Collect();

        context.RegisterSourceOutput(schemaValues, static (productionContext, schemas) =>
        {
            if (schemas.IsDefaultOrEmpty)
            {
                return;
            }

            try
            {
                var model = SchemaModel.Parse(schemas[0]!);
                if (!ValidateModel(model, productionContext))
                {
                    return;
                }

                var source = MitsubishiTagClientEmitter.Emit(model);
                productionContext.AddSource("MitsubishiTagClient.g.cs", SourceText.From(source, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                productionContext.ReportDiagnostic(Diagnostic.Create(
                    GenerationFailureDiagnostic,
                    Location.None,
                    ex.Message));
            }
        });

        var propertyBindings = context.SyntaxProvider.ForAttributeWithMetadataName(
                "MitsubishiRx.MitsubishiTagAttribute",
                predicate: static (node, _) => node is PropertyDeclarationSyntax,
                transform: static (syntaxContext, _) => ExtractPropertyBinding(syntaxContext))
            .Where(static binding => binding is not null)
            .Collect();

        context.RegisterSourceOutput(propertyBindings, static (productionContext, bindings) =>
        {
            if (bindings.IsDefaultOrEmpty)
            {
                return;
            }

            var nonNullBindings = bindings
                .Where(static binding => binding is not null)
                .Select(static binding => binding!)
                .ToArray();
            var source = MitsubishiTagClientEmitter.EmitPropertyBindings(nonNullBindings);
            productionContext.AddSource("MitsubishiTagBindings.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    /// <summary>Extracts one property-level logical-tag binding.</summary>
    /// <param name="context">The generator attribute context.</param>
    /// <returns>The binding model.</returns>
    private static PropertyBindingModel? ExtractPropertyBinding(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IPropertySymbol property || context.Attributes.Length == 0)
        {
            return null;
        }

        var attribute = context.Attributes[0];
        var tagName = attribute.ConstructorArguments.Length > 0
            ? attribute.ConstructorArguments[0].Value as string
            : null;
        if (string.IsNullOrWhiteSpace(tagName))
        {
            return null;
        }

        var clientMemberName = "LogicalTags";
        var clientAttribute = property.ContainingType.GetAttributes().FirstOrDefault(static candidate =>
            candidate.AttributeClass?.ToDisplayString() == "MitsubishiRx.MitsubishiTagClientAttribute");
        if (clientAttribute?.ConstructorArguments.Length > 0 &&
            clientAttribute.ConstructorArguments[0].Value is string configuredMemberName &&
            !string.IsNullOrWhiteSpace(configuredMemberName))
        {
            clientMemberName = configuredMemberName;
        }

        return new PropertyBindingModel(
            property.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : property.ContainingNamespace.ToDisplayString(),
            property.ContainingType.Name,
            property.Name,
            property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            tagName!,
            clientMemberName);
    }

    /// <summary>Validates a parsed schema model.</summary>
    /// <param name="model">Parsed schema model.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when the model is valid.</returns>
    private static bool ValidateModel(SchemaModel model, SourceProductionContext context)
    {
        var isValid = true;
        var sanitizedTagNames = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        var sanitizedGroupNames = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        isValid &= ValidateTags(model.Tags, context, sanitizedTagNames);

        var knownTags = new HashSet<string>(
            model.Tags.Where(static tag => !string.IsNullOrWhiteSpace(tag.Name)).Select(static tag => tag.Name),
            StringComparer.OrdinalIgnoreCase);
        isValid &= ValidateGroups(model.Groups, knownTags, context, sanitizedGroupNames);

        ReportSanitizedCollisions(context, sanitizedTagNames, "tag names", ref isValid);
        ReportSanitizedCollisions(context, sanitizedGroupNames, "group names", ref isValid);

        return isValid;
    }

    /// <summary>Validates tag entries.</summary>
    /// <param name="tags">Tag entries.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="sanitizedTagNames">Sanitized tag name index.</param>
    /// <returns><c>true</c> when all tags are valid.</returns>
    private static bool ValidateTags(
        IReadOnlyList<TagModel> tags,
        SourceProductionContext context,
        Dictionary<string, List<string>> sanitizedTagNames)
    {
        var isValid = true;
        var seenTags = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var tag in tags)
        {
            isValid &= ValidateTag(tag, context, seenTags, sanitizedTagNames);
        }

        return isValid;
    }

    /// <summary>Validates one tag entry.</summary>
    /// <param name="tag">Tag entry.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenTags">Observed tag names.</param>
    /// <param name="sanitizedTagNames">Sanitized tag name index.</param>
    /// <returns><c>true</c> when the tag is valid.</returns>
    private static bool ValidateTag(
        TagModel tag,
        SourceProductionContext context,
        HashSet<string> seenTags,
        Dictionary<string, List<string>> sanitizedTagNames)
    {
        if (string.IsNullOrWhiteSpace(tag.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyTagNameDiagnostic, Location.None));
            return false;
        }

        var isValid = true;
        if (!seenTags.Add(tag.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(DuplicateTagDiagnostic, Location.None, tag.Name));
            isValid = false;
        }

        if (!string.IsNullOrWhiteSpace(tag.DataType) && !SupportedDataTypes.Contains(tag.DataType!))
        {
            context.ReportDiagnostic(
                Diagnostic.Create(UnsupportedDataTypeDiagnostic, Location.None, tag.Name, tag.DataType));
            isValid = false;
        }

        AddSanitizedName(sanitizedTagNames, MitsubishiTagClientEmitter.SanitizeIdentifier(tag.Name), tag.Name);
        return isValid;
    }

    /// <summary>Validates group entries.</summary>
    /// <param name="groups">Group entries.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when all groups are valid.</returns>
    private static bool ValidateGroups(
        IReadOnlyList<GroupModel> groups,
        HashSet<string> knownTags,
        SourceProductionContext context,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        var isValid = true;
        var seenGroups = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var group in groups)
        {
            isValid &= ValidateGroup(group, knownTags, context, seenGroups, sanitizedGroupNames);
        }

        return isValid;
    }

    /// <summary>Validates one group entry.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenGroups">Observed group names.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when the group is valid.</returns>
    private static bool ValidateGroup(
        GroupModel group,
        HashSet<string> knownTags,
        SourceProductionContext context,
        HashSet<string> seenGroups,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        var isValid = ValidateGroupName(group, context, seenGroups, sanitizedGroupNames);

        if (group.TagNames.Count == 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupMembershipDiagnostic, Location.None, group.Name));
            isValid = false;
        }

        isValid &= ValidateGroupTagReferences(group, knownTags, context);
        return isValid;
    }

    /// <summary>Validates one group name.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="context">Source production context.</param>
    /// <param name="seenGroups">Observed group names.</param>
    /// <param name="sanitizedGroupNames">Sanitized group name index.</param>
    /// <returns><c>true</c> when the group name is valid.</returns>
    private static bool ValidateGroupName(
        GroupModel group,
        SourceProductionContext context,
        HashSet<string> seenGroups,
        Dictionary<string, List<string>> sanitizedGroupNames)
    {
        if (string.IsNullOrWhiteSpace(group.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupNameDiagnostic, Location.None));
            return false;
        }

        var isValid = true;
        if (!seenGroups.Add(group.Name))
        {
            context.ReportDiagnostic(Diagnostic.Create(DuplicateGroupDiagnostic, Location.None, group.Name));
            isValid = false;
        }

        AddSanitizedName(sanitizedGroupNames, MitsubishiTagClientEmitter.SanitizeIdentifier(group.Name), group.Name);
        return isValid;
    }

    /// <summary>Validates all tag references for one group.</summary>
    /// <param name="group">Group entry.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when all references are valid.</returns>
    private static bool ValidateGroupTagReferences(
        GroupModel group,
        HashSet<string> knownTags,
        SourceProductionContext context)
    {
        var isValid = true;
        var seenGroupTagNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var tagName in group.TagNames)
        {
            isValid &= ValidateGroupTagReference(group.Name, tagName, knownTags, seenGroupTagNames, context);
        }

        return isValid;
    }

    /// <summary>Validates one group tag reference.</summary>
    /// <param name="groupName">Group name.</param>
    /// <param name="tagName">Referenced tag name.</param>
    /// <param name="knownTags">Known tag names.</param>
    /// <param name="seenGroupTagNames">Observed tag references for this group.</param>
    /// <param name="context">Source production context.</param>
    /// <returns><c>true</c> when the reference is valid.</returns>
    private static bool ValidateGroupTagReference(
        string groupName,
        string tagName,
        HashSet<string> knownTags,
        HashSet<string> seenGroupTagNames,
        SourceProductionContext context)
    {
        if (string.IsNullOrWhiteSpace(tagName))
        {
            context.ReportDiagnostic(Diagnostic.Create(EmptyGroupTagReferenceDiagnostic, Location.None, groupName));
            return false;
        }

        if (!seenGroupTagNames.Add(tagName))
        {
            context.ReportDiagnostic(
                Diagnostic.Create(DuplicateGroupTagReferenceDiagnostic, Location.None, groupName, tagName));
            return false;
        }

        if (knownTags.Contains(tagName))
        {
            return true;
        }

        context.ReportDiagnostic(Diagnostic.Create(UnknownGroupTagDiagnostic, Location.None, groupName, tagName));
        return false;
    }

    /// <summary>Adds an original name to the sanitized identifier index.</summary>
    /// <param name="index">Sanitized identifier index.</param>
    /// <param name="sanitizedName">Sanitized identifier.</param>
    /// <param name="originalName">Original schema name.</param>
    private static void AddSanitizedName(
        Dictionary<string, List<string>> index,
        string sanitizedName,
        string originalName)
    {
        if (!index.TryGetValue(sanitizedName, out var originals))
        {
            originals = [];
            index[sanitizedName] = originals;
        }

        originals.Add(originalName);
    }

    /// <summary>Reports generated identifier collisions.</summary>
    /// <param name="context">Source production context.</param>
    /// <param name="index">Sanitized identifier index.</param>
    /// <param name="entityKind">Entity kind for diagnostics.</param>
    /// <param name="isValid">Current validation result.</param>
    private static void ReportSanitizedCollisions(
        SourceProductionContext context,
        Dictionary<string, List<string>> index,
        string entityKind,
        ref bool isValid)
    {
        foreach (var pair in index)
        {
            var distinctOriginals = pair.Value.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
            if (distinctOriginals.Length <= 1)
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                SanitizedIdentifierCollisionDiagnostic,
                Location.None,
                pair.Key,
                entityKind,
                string.Join(", ", distinctOriginals)));
            isValid = false;
        }
    }

    /// <summary>Returns whether the attribute syntax may be the generator schema attribute.</summary>
    /// <param name="attribute">Attribute syntax.</param>
    /// <returns><c>true</c> when the attribute may be the schema attribute.</returns>
    private static bool MightBeSchemaAttribute(AttributeSyntax attribute)
    {
        var name = attribute.Name.ToString();
        return name.Contains("MitsubishiTagClientSchema", StringComparison.Ordinal);
    }

    /// <summary>Extracts the schema JSON literal from a schema attribute.</summary>
    /// <param name="syntaxContext">Generator syntax context.</param>
    /// <returns>Schema JSON when one can be read.</returns>
    private static string? ExtractSchemaLiteral(GeneratorSyntaxContext syntaxContext)
    {
        if (syntaxContext.Node is not AttributeSyntax attribute ||
            attribute.ArgumentList is null ||
            attribute.ArgumentList.Arguments.Count == 0)
        {
            return null;
        }

        var expression = attribute.ArgumentList.Arguments[0].Expression;
        var constant = syntaxContext.SemanticModel.GetConstantValue(expression);
        if (constant.HasValue && constant.Value is string text)
        {
            return text;
        }

        return expression is LiteralExpressionSyntax literal ? literal.Token.ValueText : null;
    }
}
